import Link from "next/link";

export const metadata={title:"Consumer Terms of Service | My Portland Wedding"};
export default function ConsumerTerms(){return <main><section className="pagehero coupleHero"><div className="container narrow"><span className="eyebrow">For couples & consumers</span><h1>Consumer Terms of Service</h1><p className="meta">Effective September 11, 2026 · Last updated September 11, 2026</p></div></section><section className="section"><article className="container narrow legalPage">
<div className="legalHighlight"><strong>Important</strong><p>My Portland Wedding helps consumers discover and contact independent wedding vendors and use planning tools. We are not a party to contracts you enter into with a vendor, and a listing or featured placement is not a guarantee of a vendor's services.</p></div>
<p>These Consumer Terms of Service apply to couples, wedding-planning participants and other consumers who use My Portland Wedding (the “Platform”). They supplement our <Link href="/terms-of-use">Terms of Use</Link> and <Link href="/privacy-policy">Privacy Policy</Link>. By creating a consumer account or using consumer account features, you agree to these terms.</p>
<h2>1. Consumer accounts</h2><p>You must be at least 18 years old to create an account. You agree to provide accurate information, keep your credentials secure and promptly update information that materially changes. You are responsible for activity through your account.</p>
<h2>2. Free consumer features</h2><p>Consumer accounts may include vendor search, favorites, inquiries, reviews, budgets, guest lists, checklists and other wedding-planning tools. Unless a specific feature clearly states otherwise before purchase, creating a standard couple account does not enroll you in a paid vendor membership or recurring vendor subscription.</p>
<h2>3. Independent vendors</h2><p>Wedding venues and professionals listed on the Platform are independent businesses. My Portland Wedding does not employ, control or supervise them and is not a party to contracts between consumers and vendors. Before hiring or paying a vendor, you should independently review the vendor's pricing, availability, contract, insurance, licensing where applicable, deposit, refund and cancellation terms.</p>
<h2>4. Featured vendors and advertising</h2><p>Some businesses pay for memberships that may include featured placement, badges, category priority or promotional exposure. Paid or featured placement does not constitute a guarantee, certification or warranty. Editorial features may also be selected independently by My Portland Wedding.</p>
<h2>5. Inquiries and communications</h2><p>When you send an inquiry through the Platform, the information you submit is shared with the vendor you selected so that vendor can respond. Vendors are responsible for their own communications and privacy practices after receiving an inquiry. Do not send payment-card numbers, government identification numbers or other unnecessary sensitive information through inquiry messages.</p>
<h2>6. Reviews</h2><p>Reviews must be based on your genuine experience and must not contain knowingly false statements, unlawful threats, harassment, spam, confidential information or content unrelated to the reviewed business. We may moderate, decline or remove content that violates our policies or applicable law. We do not guarantee publication or continued display of every review.</p>
<h2>7. Planning tools and information</h2><p>Budgets, guest lists, checklists, timelines, articles and calculators are organizational and informational tools only. They are not legal, financial, tax, insurance or other professional advice. You are responsible for verifying important deadlines, costs and decisions.</p>
<h2>8. Your content</h2><p>You retain ownership of content you submit. You represent that you have the right to submit it and grant My Portland Wedding a non-exclusive, worldwide, royalty-free license to host, display, reproduce, resize and format that content as reasonably necessary to operate the feature in which you submitted it.</p>
<h2>9. Acceptable use</h2><p>You may not use the Platform to commit fraud, impersonate another person, manipulate reviews, harass vendors or users, distribute malware, gain unauthorized access, conduct unreasonable automated scraping or otherwise violate applicable law or materially interfere with the Platform.</p>
<h2>10. Transactions with vendors</h2><p>Payments, deposits, refunds, cancellations, rescheduling, performance disputes and other terms for wedding services are governed by the agreement between you and the applicable vendor unless My Portland Wedding expressly states that it is the seller of a particular service. My Portland Wedding is not responsible for funds paid directly to an independent vendor.</p>
<h2>11. Account suspension or closure</h2><p>We may restrict or terminate access for fraud, material violations of these terms, unlawful activity, abuse of other users or conduct that creates material security or operational risk. You may contact us if you want assistance with your consumer account. Certain records may be retained as described in our Privacy Policy.</p>
<h2>12. Disclaimers and liability</h2><p>To the extent permitted by law, the Platform is provided “as is” and “as available.” We do not guarantee vendor availability, pricing, performance, results or the accuracy of every third-party listing. To the fullest extent permitted by law, My Portland Wedding is not liable for indirect, incidental, special, consequential, exemplary or punitive damages arising from use of the Platform or transactions with independent vendors. Nothing here limits rights or liability that cannot legally be limited.</p>
<h2>13. Changes and governing law</h2><p>We may update these Consumer Terms periodically and will post the current version and updated date. These terms are governed by Oregon law, except where applicable law requires otherwise.</p>
<h2>14. Contact</h2><p>Questions about consumer accounts or these terms may be sent to <a href="mailto:hello@myportlandwedding.com">hello@myportlandwedding.com</a>.</p>
<p className="legalNote">Also review our <Link href="/terms-of-use">Terms of Use</Link> and <Link href="/privacy-policy">Privacy Policy</Link>. Paid wedding professionals are separately subject to our <Link href="/vendor-terms">Vendor Terms of Service</Link>.</p>
</article></section></main>}
