create extension if not exists "uuid-ossp";

create table if not exists markets (
  id uuid primary key default uuid_generate_v4(),
  slug text unique not null,
  name text not null,
  domain text unique,
  city text,
  state text,
  active boolean default true,
  created_at timestamptz default now()
);

create table if not exists vendor_profiles (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references auth.users(id) on delete cascade,
  market_slug text not null default 'portland',
  slug text unique not null,
  business_name text not null,
  primary_category text not null,
  secondary_categories text[] default '{}',
  description text,
  email text,
  phone text,
  website text,
  instagram text,
  facebook text,
  tiktok text,
  pinterest text,
  youtube text,
  video_urls text[] not null default '{}',
  city text,
  state text,
  service_cities text[] not null default '{}',
  service_radius integer,
  pricing_from numeric,
  pricing_typical numeric,
  pricing_max numeric,
  wedding_styles text[] not null default '{}',
  guest_capacity_min integer,
  guest_capacity_max integer,
  pricing_packages jsonb not null default '[]'::jsonb,
  plan text check (plan in ('free','basic','professional','premium')) default 'free',
  founding_vendor boolean not null default false,
  founding_vendor_position smallint check (founding_vendor_position is null or founding_vendor_position between 1 and 5),
  founding_vendor_category text,
  founding_vendor_activated_at timestamptz,
  founding_vendor_forfeited_at timestamptz,
  status text check (status in ('draft','pending','active','suspended')) default 'draft',
  rating numeric default 0,
  review_count integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);


create table if not exists founding_vendor_memberships (
  id uuid primary key default uuid_generate_v4(),
  market_slug text not null default 'portland' references markets(slug),
  category text not null,
  position smallint not null check (position between 1 and 5),
  reservation_email text,
  vendor_id uuid unique references vendor_profiles(id) on delete set null,
  status text not null default 'reserved' check (status in ('reserved','active','forfeited')),
  reserved_until timestamptz, activated_at timestamptz, forfeited_at timestamptz,
  created_at timestamptz default now(), updated_at timestamptz default now(),
  unique(market_slug,category,position)
);

create table if not exists vendor_photos (
  id uuid primary key default uuid_generate_v4(),
  vendor_id uuid references vendor_profiles(id) on delete cascade,
  storage_path text not null,
  sort_order integer default 0,
  created_at timestamptz default now()
);

create table if not exists subscriptions (
  id uuid primary key default uuid_generate_v4(),
  vendor_id uuid references vendor_profiles(id) on delete set null,
  market_slug text not null default 'portland',
  plan text check (plan in ('basic','professional','premium')),
  status text,
  stripe_customer_id text,
  stripe_subscription_id text unique,
  current_period_end timestamptz,
  created_at timestamptz default now()
);

create table if not exists leads (
  id uuid primary key default uuid_generate_v4(),
  vendor_id uuid references vendor_profiles(id) on delete set null,
  vendor_slug text,
  market_slug text not null default 'portland',
  name text not null,
  email text not null,
  wedding_date date,
  message text,
  status text default 'new',
  created_at timestamptz default now()
);

create table if not exists reviews (
  id uuid primary key default uuid_generate_v4(),
  vendor_id uuid references vendor_profiles(id) on delete cascade,
  reviewer_user_id uuid references auth.users(id) on delete set null,
  rating integer check (rating between 1 and 5),
  title text,
  body text,
  status text default 'pending',
  created_at timestamptz default now()
);

create table if not exists favorites (
  id uuid primary key default uuid_generate_v4(),
  user_id uuid references auth.users(id) on delete cascade,
  vendor_id uuid references vendor_profiles(id) on delete cascade,
  created_at timestamptz default now(),
  unique(user_id, vendor_id)
);

create table if not exists analytics_events (
  id bigint generated by default as identity primary key,
  market_slug text not null default 'portland',
  vendor_id uuid references vendor_profiles(id) on delete set null,
  event_type text not null,
  session_id text,
  created_at timestamptz default now()
);

insert into markets (slug,name,domain,city,state)
values ('portland','My Portland Wedding','myportlandwedding.com','Portland','OR')
on conflict (slug) do nothing;

alter table vendor_profiles enable row level security;
alter table founding_vendor_memberships enable row level security;
alter table vendor_photos enable row level security;
alter table subscriptions enable row level security;
alter table leads enable row level security;
alter table reviews enable row level security;
alter table favorites enable row level security;

create policy "public active vendors"
on vendor_profiles for select using (status='active');

create policy "vendors manage own profile"
on vendor_profiles for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "public approved reviews"
on reviews for select using (status='approved');

create policy "users manage own favorites"
on favorites for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
