import Link from "next/link";
import { redirect } from "next/navigation";
import { createSupabaseServerClient } from "../../../lib/supabase/server";
import { decodeDisplayText } from "../../../lib/text";
import { plans } from "../../../lib/site";

const stages=["lead","sold","setup_sent","payment_pending","active","paused","lost"];
export default async function AdminVendors({searchParams}:{searchParams:Promise<{q?:string,status?:string,plan?:string,stage?:string,account?:string,message?:string}>}){
 const params=await searchParams; const supabase=await createSupabaseServerClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) redirect("/admin/login");
 const {data:admin}=await supabase.from("admin_users").select("user_id").eq("user_id",user.id).maybeSingle(); if(!admin) redirect("/admin/login?error=Admin%20access%20required");
 let query=supabase.from("vendor_profiles").select("id,business_name,email,phone,website,plan,status,listing_state,primary_category,city,state,service_cities,crm_stage,last_contact_at,next_follow_up_at,created_at,updated_at").eq("market_slug","portland").order("created_at",{ascending:false});
 if(params.status) query=query.eq("status",params.status); if(params.plan) query=query.eq("plan",params.plan); if(params.stage) query=query.eq("crm_stage",params.stage);
 if(params.account==="paid") query=query.neq("plan","free");
 if(params.account==="self_free") query=query.eq("plan","free").eq("listing_state","claimed");
 if(params.account==="complimentary") query=query.eq("plan","free").in("listing_state",["unclaimed","claim_pending"]);
 if(params.q){ const safe=params.q.replaceAll(",",""); query=query.or(`business_name.ilike.%${safe}%,email.ilike.%${safe}%,phone.ilike.%${safe}%`); }
 const {data:vendors}=await query;
 return <main><section className="pagehero"><div className="container"><span className="eyebrow">Administration</span><h1>Vendor CRM</h1><p>Search, manage and maintain every vendor account from one place.</p></div></section><section className="section"><div className="container">
  <div className="adminCrmTopbar"><Link className="btn light" href="/admin">← Admin Home</Link><a className="btn primary" href="/admin#sales-onboarding">+ Add Vendor</a></div>
  <div className="crmAccountQuickFilters" aria-label="Vendor account type filters"><Link className={`btn ${!params.account?"primary":"light"}`} href="/admin/vendors">All</Link><Link className={`btn ${params.account==="paid"?"primary":"light"}`} href="/admin/vendors?account=paid">Paid</Link><Link className={`btn ${params.account==="self_free"?"primary":"light"}`} href="/admin/vendors?account=self_free">Free · Self Listed</Link><Link className={`btn ${params.account==="complimentary"?"primary":"light"}`} href="/admin/vendors?account=complimentary">Complimentary · MPW Added</Link></div>
  {params.message&&<div className="notice success">{params.message}</div>}
  <form className="crmFilters" method="get">{params.account&&<input type="hidden" name="account" value={params.account}/>}<input name="q" defaultValue={params.q||""} placeholder="Search business, email or phone"/><select name="status" defaultValue={params.status||""}><option value="">All listing statuses</option><option value="active">Active</option><option value="pending">Pending</option><option value="draft">Draft</option><option value="suspended">Suspended</option></select><select name="plan" defaultValue={params.plan||""}><option value="">All plans</option>{Object.entries(plans).map(([k,p])=><option key={k} value={k}>{p.name}</option>)}</select><select name="stage" defaultValue={params.stage||""}><option value="">All CRM stages</option>{stages.map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select><button className="btn primary">Filter</button><Link className="btn light" href="/admin/vendors">Clear</Link></form>
  <div className="panel dashboardPanel"><div className="crmSectionHeader"><div><span className="eyebrow">Accounts</span><h2>{vendors?.length||0} vendors</h2></div></div><div className="tableWrap"><table className="crmTable"><thead><tr><th>Vendor</th><th>Account type</th><th>Plan</th><th>Listing</th><th>CRM stage</th><th>Next follow-up</th><th></th></tr></thead><tbody>{(vendors||[]).map((v:any)=><tr key={v.id}><td><strong>{decodeDisplayText(v.business_name)}</strong><br/><span className="meta">{v.email||"No email"}{v.phone?` · ${v.phone}`:""}</span></td><td>{v.plan!=="free"?<span className="accountTypeBadge account-paid">Paid</span>:v.listing_state==="claimed"?<span className="accountTypeBadge account-self-free">Free · Self Listed</span>:<span className="accountTypeBadge account-complimentary">Complimentary · MPW Added</span>}</td><td>{plans[v.plan as keyof typeof plans]?.name||v.plan}</td><td><span className={`pipelineStatus status-${v.status}`}>{v.status}</span></td><td><span className={`pipelineStatus status-${v.crm_stage||"lead"}`}>{(v.crm_stage||"lead").replaceAll("_"," ")}</span></td><td>{v.next_follow_up_at?new Date(v.next_follow_up_at).toLocaleDateString():"—"}</td><td><div className="crmRowActions"><Link className="btn light" href={`/admin/vendors/${v.id}`}>Manage</Link><Link className="btn light" href={`/vendor/dashboard?admin_preview=${v.id}`}>Preview</Link></div></td></tr>)}</tbody></table></div>{!vendors?.length&&<p className="meta">No vendors match those filters.</p>}</div>
 </div></section></main>
}
