import Link from "next/link";
import { redirect } from "next/navigation";
import { createSupabaseServerClient } from "../../../lib/supabase/server";
import { createAdminClient } from "../../../lib/supabase/admin";
import { decodeDisplayText } from "../../../lib/text";

const daysFor=(r:string)=>r==='7'?7:r==='90'?90:r==='365'?365:30;
const pct=(n:number,d:number)=>d?`${Math.round(n/d*100)}%`:'—';
const planLabel=(plan:string,founding:boolean)=>founding?'Founding':plan==='free'?'Listed':plan==='basic'?'Supported':plan==='professional'?'Professional':plan==='premium'?'Premium':plan||'—';

export default async function AnalyticsCenter({searchParams}:{searchParams:Promise<{range?:string,q?:string}>}){
 const q=await searchParams; const range=['7','30','90','365'].includes(q.range||'')?q.range!:'30'; const days=daysFor(range); const filter=(q.q||'').trim().toLowerCase();
 const s=await createSupabaseServerClient(); const {data:{user}}=await s.auth.getUser(); if(!user)redirect('/admin/login');
 const {data:a}=await s.from('admin_users').select('user_id').eq('user_id',user.id).maybeSingle(); if(!a)redirect('/admin');
 const db=createAdminClient(),since=new Date(Date.now()-days*86400000).toISOString();
 const [vendors,couples,profiles,matches,leads,favorites,subs,builderSaves]=await Promise.all([
  db.from('vendor_profiles').select('id,slug,business_name,plan,status,primary_category,city,state,founding_vendor,created_at').eq('market_slug','portland'),
  db.from('couple_profiles').select('user_id').eq('market_slug','portland'),
  db.from('analytics_events').select('vendor_id,event_type,created_at').eq('market_slug','portland').in('event_type',['profile_view','builder_profile_view','contact_phone_profile','contact_phone_wedding_builder','contact_email_profile','contact_email_wedding_builder','contact_website_profile','contact_website_wedding_builder','contact_social_instagram_profile','contact_social_instagram_wedding_builder','contact_social_facebook_profile','contact_social_facebook_wedding_builder','contact_social_tiktok_profile','contact_social_tiktok_wedding_builder','contact_social_pinterest_profile','contact_social_pinterest_wedding_builder','contact_social_youtube_profile','contact_social_youtube_wedding_builder']).gte('created_at',since),
  db.from('wedding_builder_match_events').select('builder_session_id,vendor_id,wedding_budget,city,wedding_style,created_at').gte('created_at',since),
  db.from('leads').select('id,vendor_id,source,status,created_at').eq('market_slug','portland').gte('created_at',since),
  db.from('favorites').select('id,vendor_id,created_at').gte('created_at',since),
  db.from('subscriptions').select('vendor_id,plan,status'),
  db.from('analytics_events').select('vendor_id,event_type,created_at').eq('market_slug','portland').eq('event_type','builder_save').gte('created_at',since)
 ]);
 const vs=vendors.data||[],cs=couples.data||[],views=profiles.data||[],ms=matches.data||[],ls=leads.data||[],fs=favorites.data||[],ss=subs.data||[],bs=builderSaves.data||[];
 const builderViews=views.filter((x:any)=>x.event_type==='builder_profile_view'); const totalViews=views.filter((x:any)=>x.event_type==='profile_view'); const contacts=views.filter((x:any)=>String(x.event_type).startsWith('contact_')); const phoneClicks=contacts.filter((x:any)=>String(x.event_type).startsWith('contact_phone_')); const emailClicks=contacts.filter((x:any)=>String(x.event_type).startsWith('contact_email_')); const websiteClicks=contacts.filter((x:any)=>String(x.event_type).startsWith('contact_website_')); const socialClicks=contacts.filter((x:any)=>String(x.event_type).startsWith('contact_social_'));
 const sessions=new Set(ms.map((m:any)=>m.builder_session_id).filter(Boolean)); const builderLeads=ls.filter((l:any)=>l.source==='wedding_builder'); const paid=vs.filter((v:any)=>v.plan!=='free'&&v.status==='active');
 const prices:any={basic:35,professional:45,premium:55}; const mrr=ss.filter((x:any)=>['active','trialing'].includes(String(x.status))).reduce((n:number,x:any)=>n+(prices[x.plan]||0),0);
 const vm=new Map(vs.map((v:any)=>[v.id,v])); const countBy=(rows:any[],key='vendor_id')=>{const m=new Map<string,number>();rows.forEach((x:any)=>{const id=x[key];if(id)m.set(id,(m.get(id)||0)+1)});return m};
 const viewMap=countBy(totalViews),matchMap=countBy(ms),leadMap=countBy(ls),saveMap=countBy(fs),builderLeadMap=countBy(builderLeads),builderViewMap=countBy(builderViews),builderSaveMap=countBy(bs),phoneMap=countBy(phoneClicks),emailMap=countBy(emailClicks),websiteMap=countBy(websiteClicks),socialMap=countBy(socialClicks);
 const vendorRows=vs.map((v:any)=>{const pv=viewMap.get(v.id)||0,ap=matchMap.get(v.id)||0,ld=leadMap.get(v.id)||0,sv=saveMap.get(v.id)||0,bl=builderLeadMap.get(v.id)||0,bv=builderViewMap.get(v.id)||0,bsave=builderSaveMap.get(v.id)||0;const phone=phoneMap.get(v.id)||0,email=emailMap.get(v.id)||0,website=websiteMap.get(v.id)||0,social=socialMap.get(v.id)||0;return {...v,profileViews:pv,appearances:ap,leads:ld,saves:sv,builderLeads:bl,builderViews:bv,builderSaves:bsave,phoneClicks:phone,emailClicks:email,websiteClicks:website,socialClicks:social,contactActions:phone+email+website+social,viewRate:ap?Math.round(bv/ap*100):null,saveRate:ap?Math.round(bsave/ap*100):null,leadRate:ap?Math.round(bl/ap*100):null,engagement:pv+sv+ld};}).filter((v:any)=>!filter||String(v.business_name||'').toLowerCase().includes(filter)||String(v.primary_category||'').toLowerCase().includes(filter)).sort((a:any,b:any)=>b.appearances-a.appearances||b.profileViews-a.profileViews||b.leads-a.leads);
 const cats=new Map<string,{appearances:number,views:number,leads:number,saves:number,vendors:Set<string>}>(); vs.forEach((v:any)=>{if(v.primary_category&&!cats.has(v.primary_category))cats.set(v.primary_category,{appearances:0,views:0,leads:0,saves:0,vendors:new Set()})});
 vendorRows.forEach((v:any)=>{const c=v.primary_category;if(!c)return;const x=cats.get(c)||{appearances:0,views:0,leads:0,saves:0,vendors:new Set<string>()};x.appearances+=v.appearances;x.views+=v.profileViews;x.leads+=v.leads;x.saves+=v.saves;x.vendors.add(v.id);cats.set(c,x)});
 const top=[...cats.entries()].sort((a,b)=>b[1].appearances-a[1].appearances).slice(0,12),max=Math.max(1,...top.map(x=>x[1].appearances));
 const avg=ms.length?Math.round(ms.reduce((n:number,m:any)=>n+(Number(m.wedding_budget)||0),0)/ms.length):0;
 const cards=[['Vendor profile views',totalViews.length,'Selected period'],['Wedding Builder results',sessions.size,'Unique completed roster sessions'],['Vendor appearances',ms.length,`${new Set(ms.map((m:any)=>m.vendor_id)).size} vendors appeared`],['Qualified leads',ls.length,`${builderLeads.length} from Wedding Builder`],['Contact actions',contacts.length,`${phoneClicks.length} phone · ${emailClicks.length} email · ${websiteClicks.length} website · ${socialClicks.length} social`],['Builder lead conversion',pct(builderLeads.length,sessions.size),'Completed Builders → Builder leads'],['Vendor saves',fs.length,'Couple favorites'],['Active paid vendors',paid.length,`${vs.length} total vendor accounts`],['Estimated MRR',`$${mrr.toLocaleString()}`,'Active subscriptions at plan rates'],['Couple accounts',cs.length,'All-time Portland accounts'],['Average Builder budget',avg?`$${avg.toLocaleString()}`:'—','Selected period']];
 return <main><section className="pagehero"><div className="container"><span className="eyebrow">My Portland Wedding</span><h1>Analytics Center</h1><p>Marketplace performance from Wedding Builder exposure through vendor engagement and leads.</p></div></section><section className="section"><div className="container">
  <div className="adminCrmTopbar"><Link className="btn light" href="/admin">← Marketplace Admin</Link></div>
  <div className="analyticsToolbar">{[['7','7 days'],['30','30 days'],['90','90 days'],['365','1 year']].map(([v,l])=><a key={v} className={range===v?'active':''} href={`/admin/analytics?range=${v}`}>{l}</a>)}</div>
  <div className="analyticsGrid">{cards.map(([label,value,note]:any)=><div className="panel analyticsCard" key={label}><span>{label}</span><strong>{typeof value==='number'?value.toLocaleString():value}</strong><small>{note}</small></div>)}</div>
  <section className="panel dashboardPanel analyticsSection"><div className="crmSectionHeader"><div><span className="eyebrow">Vendor performance</span><h2>Who is getting seen — and what happens next</h2><p className="meta">Profile views, Wedding Builder appearances, saves and leads for every MPW vendor in the selected period.</p></div></div>
   <form className="crmFilters" method="get"><input type="hidden" name="range" value={range}/><input name="q" defaultValue={q.q||''} placeholder="Search vendor or category"/><button className="btn primary">Filter</button>{q.q&&<Link className="btn light" href={`/admin/analytics?range=${range}`}>Clear</Link>}</form>
   <div className="tableWrap"><table className="crmTable analyticsVendorTable"><thead><tr><th>Vendor</th><th>Tier</th><th>Builder appearances</th><th>Profile views</th><th>Builder profile views</th><th>Saves</th><th>Builder saves</th><th>Leads</th><th>Builder leads</th><th>Contact actions</th><th>Phone</th><th>Email</th><th>Website</th><th>Social</th><th>View / appearance</th><th>Save / appearance</th><th>Builder lead / appearance</th><th></th></tr></thead><tbody>{vendorRows.map((v:any)=><tr key={v.id}><td><strong>{decodeDisplayText(v.business_name)}</strong><br/><span className="meta">{decodeDisplayText(v.primary_category||'Wedding Vendor')}{v.city?` · ${decodeDisplayText(v.city)}, ${v.state||'OR'}`:''}</span></td><td>{planLabel(v.plan,!!v.founding_vendor)}</td><td><strong>{v.appearances}</strong></td><td><strong>{v.profileViews}</strong></td><td><strong>{v.builderViews}</strong></td><td>{v.saves}</td><td>{v.builderSaves}</td><td>{v.leads}</td><td>{v.builderLeads}</td><td><strong>{v.contactActions}</strong></td><td>{v.phoneClicks}</td><td>{v.emailClicks}</td><td>{v.websiteClicks}</td><td>{v.socialClicks}</td><td>{v.viewRate===null?'—':`${v.viewRate}%`}</td><td>{v.saveRate===null?'—':`${v.saveRate}%`}</td><td>{v.leadRate===null?'—':`${v.leadRate}%`}</td><td><Link className="btn light" href={`/admin/vendors/${v.id}`}>Vendor →</Link></td></tr>)}</tbody></table></div>{!vendorRows.length&&<p className="meta">No vendors match this filter.</p>}
  </section>
  <section className="panel dashboardPanel analyticsSection"><span className="eyebrow">Wedding Builder demand</span><h2>Category activity</h2><p className="meta">See where couple demand is landing and whether those appearances are turning into attention.</p><div className="analyticsRows">{top.length?top.map(([cat,x])=><div className="analyticsRow" key={cat}><strong>{decodeDisplayText(cat)}</strong><div className="analyticsBar"><i style={{width:`${Math.max(3,x.appearances/max*100)}%`}}/></div><span>{x.appearances} appearances · {x.views} views · {x.saves} saves · {x.leads} leads</span></div>):<p className="meta">No Wedding Builder activity in this period yet.</p>}</div></section>
  <section className="panel dashboardPanel analyticsSection"><span className="eyebrow">Funnel</span><h2>Wedding Builder → vendor outcome</h2><div className="analyticsGrid compactAnalyticsGrid"><div className="analyticsCard"><span>Completed Builders</span><strong>{sessions.size}</strong></div><div className="analyticsCard"><span>Vendor appearances</span><strong>{ms.length}</strong></div><div className="analyticsCard"><span>Builder profile views</span><strong>{builderViews.length}</strong></div><div className="analyticsCard"><span>Builder saves</span><strong>{bs.length}</strong></div><div className="analyticsCard"><span>Builder leads</span><strong>{builderLeads.length}</strong></div></div><p className="meta">Builder-attributed profile views and saves are tracked from this release forward. Historical profile views and saves remain total MPW activity because their acquisition source was not previously persisted.</p></section>
  <section className="panel dashboardPanel analyticsSection"><span className="eyebrow">Measurement note</span><h2>What MPW can verify</h2><p>These results use MPW's Supabase profile-view, Wedding Builder roster, lead, favorite, vendor, couple and subscription records. Historical Wedding Builder starts and historical profile-view acquisition sources were not persisted, so those figures are not invented. New tracking can be expanded from this point forward.</p></section>
 </div></section></main>
}
