"use client";
import {useMemo,useState} from "react";
type Vendor={id:string,business_name:string,email?:string|null,plan:string,status:string,primary_category:string,website?:string|null,instagram?:string|null,facebook?:string|null,tiktok?:string|null,pinterest?:string|null,youtube?:string|null};
type Result={status:string,summary:string,checkedAt:string,locations:{url:string,type:string,status:string,evidence:string}[]};
type Event={vendor_id:string,event_type:string,created_at:string};
export default function BadgeBacklinkCenter({vendors,badgeEvents}:{vendors:Vendor[],badgeEvents:Event[]}){
 const [results,setResults]=useState<Record<string,Result>>({}); const [running,setRunning]=useState<string[]>([]); const [q,setQ]=useState(''); const [filter,setFilter]=useState('all'); const [selected,setSelected]=useState<string[]>([]); const [sending,setSending]=useState(false); const [notice,setNotice]=useState('');
 const scan=async(v:Vendor)=>{setRunning(x=>[...x,v.id]);try{const r=await fetch('/api/admin/badge-check',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({vendor_id:v.id})});if(r.ok){const j=await r.json();setResults(x=>({...x,[v.id]:j}))}}finally{setRunning(x=>x.filter(id=>id!==v.id))}};
 const scanAll=async()=>{setNotice('');for(let i=0;i<vendors.length;i+=3) await Promise.all(vendors.slice(i,i+3).map(scan));};
 const classify=(r?:Result)=>!r?'never':r.locations.some(x=>x.status==='detected')?'found':r.locations.some(x=>x.status==='unverified')?'unverified':'not_found';
 const eventFor=(id:string,type:string)=>badgeEvents.find(e=>e.vendor_id===id&&e.event_type===type);
 const downloaded=(id:string)=>Boolean(eventFor(id,'badge_pack_download')||eventFor(id,'badge_embed_copied'));
 const eligible=(v:Vendor)=>classify(results[v.id])==='not_found'&&!downloaded(v.id)&&Boolean(v.email);
 const rows=useMemo(()=>vendors.filter(v=>{const s=classify(results[v.id]);return (!q||`${v.business_name} ${v.primary_category} ${v.plan}`.toLowerCase().includes(q.toLowerCase()))&&(filter==='all'||filter===s||(filter==='eligible'&&eligible(v)))}),[vendors,results,q,filter,badgeEvents]);
 const eligibleIds=vendors.filter(eligible).map(v=>v.id); const counts={found:vendors.filter(v=>classify(results[v.id])==='found').length,notFound:vendors.filter(v=>classify(results[v.id])==='not_found').length,unverified:vendors.filter(v=>classify(results[v.id])==='unverified').length,never:vendors.filter(v=>classify(results[v.id])==='never').length};
 const send=async()=>{const ids=selected.filter(id=>eligibleIds.includes(id));if(!ids.length)return; if(!window.confirm(`Send the Vendor Badge Package email to ${ids.length} eligible vendor${ids.length===1?'':'s'}?`))return;setSending(true);setNotice('');try{const r=await fetch('/api/admin/badge-package-email',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({vendor_ids:ids})});const j=await r.json();if(!r.ok)throw new Error(j.error||'Email send failed');setNotice(`Badge Package email: ${j.sent} sent${j.skipped?`, ${j.skipped} skipped`:''}${j.failed?`, ${j.failed} failed`:''}.`);setSelected([])}catch(e:any){setNotice(e.message||'Email send failed')}finally{setSending(false)}};
 return <><div className="adminCrmTopbar"><div className="adminAccountNav"><a className="btn light" href="/admin">← Admin Home</a><button className="btn primary" onClick={scanAll} disabled={running.length>0}>{running.length?`Scanning ${running.length}…`:'Scan All Vendors'}</button><button className="btn light" onClick={()=>setSelected(eligibleIds)} disabled={!eligibleIds.length}>Select All Eligible ({eligibleIds.length})</button><button className="btn primary" onClick={send} disabled={sending||!selected.some(id=>eligibleIds.includes(id))}>{sending?'Sending…':`Send Badge Package Email (${selected.filter(id=>eligibleIds.includes(id)).length})`}</button></div></div>
 {notice&&<div className="notice success">{notice}</div>}
 <div className="grid stats"><div className="stat"><span className="meta">Vendors</span><strong>{vendors.length}</strong></div><div className="stat"><span className="meta">MPW found</span><strong>{counts.found}</strong></div><div className="stat"><span className="meta">Not found</span><strong>{counts.notFound}</strong></div><div className="stat"><span className="meta">Eligible for email</span><strong>{eligibleIds.length}</strong></div><div className="stat"><span className="meta">Never checked</span><strong>{counts.never}</strong></div></div>
 <div className="panel dashboardPanel"><p className="meta">Email eligibility requires a completed scan with no MPW badge/backlink/mention detected, no recorded badge download/embed copy, and a vendor email address. Unverified and never-scanned vendors are not emailed automatically.</p><div className="crmFilters"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search vendor, category or plan"/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All badge statuses</option><option value="eligible">Eligible for badge email</option><option value="found">Found</option><option value="not_found">Not found / Needs attention</option><option value="unverified">Unverified</option><option value="never">Never checked</option></select></div>
 <div className="tableWrap"><table className="crmTable"><thead><tr><th></th><th>Vendor</th><th>Tier</th><th>Overall</th><th>Badge package</th><th>Website / badge / backlink evidence</th><th>Social</th><th>Last checked</th><th></th></tr></thead><tbody>{rows.map(v=>{const r=results[v.id], state=classify(r);const web=r?.locations.filter(x=>x.type==='Website')||[];const social=r?.locations.filter(x=>x.type!=='Website')||[];const access=eventFor(v.id,'badge_pack_download')||eventFor(v.id,'badge_embed_copied'), sent=eventFor(v.id,'badge_pack_sent');return <tr key={v.id}><td><input type="checkbox" checked={selected.includes(v.id)} disabled={!eligible(v)} onChange={e=>setSelected(x=>e.target.checked?[...x,v.id]:x.filter(id=>id!==v.id))}/></td><td><strong>{v.business_name}</strong><br/><span className="meta">{v.primary_category}{v.email?` · ${v.email}`:' · No email'}</span></td><td>{v.plan}</td><td><span className={`pipelineStatus status-${state==='found'?'active':state==='not_found'?'suspended':'pending'}`}>{state.replace('_',' ')}</span></td><td>{access?<><b>Accessed</b><br/><span className="meta">{new Date(access.created_at).toLocaleDateString()}</span></>:sent?<><b>Email sent</b><br/><span className="meta">{new Date(sent.created_at).toLocaleDateString()}</span></>:<span className="meta">Not accessed</span>}</td><td>{web.length?web.map((x,i)=><div key={i}><b>{x.evidence}</b>{x.url.startsWith('http')&&<> · <a href={x.url} target="_blank" rel="noreferrer">Open location</a></>}</div>):<span className="meta">Not scanned</span>}</td><td>{social.length?social.map((x,i)=><div key={i}>{x.type}: {x.status.replace('_',' ')}</div>):<span className="meta">—</span>}</td><td>{r?.checkedAt?new Date(r.checkedAt).toLocaleString():'—'}</td><td><button className="btn light" onClick={()=>scan(v)} disabled={running.includes(v.id)}>{running.includes(v.id)?'Scanning…':'Scan'}</button> <a className="btn light" href={`/admin/vendors/${v.id}`}>Vendor</a></td></tr>})}</tbody></table></div></div></>
}
