import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { createSupabaseServerClient } from "../../../../lib/supabase/server";
import { createAdminClient } from "../../../../lib/supabase/admin";
import { decodeDisplayText } from "../../../../lib/text";

const stages=["new","planning","contacting_vendors","booked_vendors","married","inactive"];
const statuses=["active","paused","archived"];
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n||0);

export default async function CoupleManage({params,searchParams}:{params:Promise<{id:string}>,searchParams:Promise<{message?:string,error?:string}>}){
 const {id}=await params; const q=await searchParams; const supabase=await createSupabaseServerClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) redirect("/admin/login");
 const {data:admin}=await supabase.from("admin_users").select("user_id").eq("user_id",user.id).maybeSingle(); if(!admin) redirect("/admin/login?error=Admin%20access%20required");
 const adminDb=createAdminClient(); const {data:authResult}=await adminDb.auth.admin.getUserById(id); const authUser=authResult?.user;
 const [{data:c},{data:budget},{data:guests},{data:favorites},{data:leads},{data:reviews}]=await Promise.all([
  adminDb.from("couple_profiles").select("*").eq("user_id",id).maybeSingle(),
  adminDb.from("planning_budget_items").select("id,category,budgeted,actual,paid").eq("user_id",id).order("sort_order",{ascending:true}),
  adminDb.from("planning_guests").select("id,party_size,rsvp_status").eq("user_id",id),
  adminDb.from("favorites").select("id,vendor_id,created_at").eq("user_id",id).order("created_at",{ascending:false}),
  adminDb.from("leads").select("id,vendor_id,name,status,source,created_at").eq("couple_user_id",id).order("created_at",{ascending:false}).limit(25),
  adminDb.from("reviews").select("id,vendor_id,rating,title,status,created_at").eq("reviewer_user_id",id).order("created_at",{ascending:false}).limit(25)
 ]); if(!c) notFound();
 const vendorIds=[...new Set([...(favorites||[]).map((x:any)=>x.vendor_id),...(leads||[]).map((x:any)=>x.vendor_id),...(reviews||[]).map((x:any)=>x.vendor_id)].filter(Boolean))]; let vendorMap=new Map<string,string>(); if(vendorIds.length){const {data:vendors}=await adminDb.from("vendor_profiles").select("id,business_name").in("id",vendorIds);vendorMap=new Map((vendors||[]).map((v:any)=>[v.id,decodeDisplayText(v.business_name)]));}
 const budgeted=(budget||[]).reduce((s:number,b:any)=>s+Number(b.budgeted||0),0), actual=(budget||[]).reduce((s:number,b:any)=>s+Number(b.actual||0),0), paid=(budget||[]).reduce((s:number,b:any)=>s+Number(b.paid||0),0);
 const guestCount=(guests||[]).reduce((s:number,g:any)=>s+Number(g.party_size||1),0), yesCount=(guests||[]).filter((g:any)=>g.rsvp_status==="yes").reduce((s:number,g:any)=>s+Number(g.party_size||1),0);
 const daysToWedding=c.wedding_date?Math.ceil((new Date(`${c.wedding_date}T12:00:00`).getTime()-Date.now())/86400000):null;
 return <main><section className="pagehero"><div className="container"><span className="eyebrow">Couple CRM</span><h1>{decodeDisplayText(c.first_name||"Couple account")}{c.partner_name?` & ${decodeDisplayText(c.partner_name)}`:""}</h1><p>{authUser?.email||"No email available"}{c.wedding_date?` · Wedding ${new Date(`${c.wedding_date}T12:00:00`).toLocaleDateString()}`:""}</p></div></section><section className="section"><div className="container"><div className="adminCrmTopbar"><Link className="btn light" href="/admin/couples">← All Couples</Link></div>{q.message&&<div className="notice success">{q.message}</div>}{q.error&&<div className="notice error">{q.error}</div>}
  <div className="grid stats coupleAdminStats"><div className="stat"><span className="meta">Wedding</span><strong>{daysToWedding===null?"Not set":daysToWedding>=0?`${daysToWedding} days`:"Passed"}</strong></div><div className="stat"><span className="meta">Budget</span><strong>{money(budgeted)}</strong></div><div className="stat"><span className="meta">Guest count</span><strong>{guestCount}</strong></div><div className="stat"><span className="meta">Saved vendors</span><strong>{favorites?.length||0}</strong></div><div className="stat"><span className="meta">Vendor inquiries</span><strong>{leads?.length||0}</strong></div></div>
  <div className="crmTwoCol coupleAdminGrid"><div>
   <div className="panel dashboardPanel"><span className="eyebrow">Planning snapshot</span><h2>Wedding progress</h2><div className="coupleAdminMetrics"><div><span>Budgeted</span><strong>{money(budgeted)}</strong></div><div><span>Actual</span><strong>{money(actual)}</strong></div><div><span>Paid</span><strong>{money(paid)}</strong></div><div><span>RSVP yes</span><strong>{yesCount}</strong></div></div><p className="meta">This overview intentionally summarizes guest-list activity without exposing individual guest contact information.</p></div>
   <div className="panel dashboardPanel"><span className="eyebrow">Marketplace activity</span><h2>Saved vendors</h2>{favorites?.length?(favorites||[]).slice(0,12).map((f:any)=><div className="crmMiniRow" key={f.id}><strong>{vendorMap.get(f.vendor_id)||"Vendor"}</strong><span className="meta">Saved {new Date(f.created_at).toLocaleDateString()}</span></div>):<p className="meta">No saved vendors yet.</p>}<h3 className="crmSubheading">Recent inquiries</h3>{leads?.length?(leads||[]).map((l:any)=><div className="crmMiniRow" key={l.id}><strong>{vendorMap.get(l.vendor_id)||"Vendor inquiry"}</strong><span>{l.status}</span><span className="meta">{l.source?.replaceAll("_"," ")||"profile"} · {new Date(l.created_at).toLocaleDateString()}</span></div>):<p className="meta">No vendor inquiries yet.</p>}<h3 className="crmSubheading">Reviews</h3>{reviews?.length?(reviews||[]).map((r:any)=><div className="crmMiniRow" key={r.id}><strong>{"★".repeat(Number(r.rating||0))} {vendorMap.get(r.vendor_id)||"Vendor"}</strong><span>{r.status}</span><span className="meta">{decodeDisplayText(r.title||"")}</span></div>):<p className="meta">No reviews submitted yet.</p>}</div>
  </div><div>
   <div className="panel dashboardPanel"><span className="eyebrow">Account</span><h2>Customer record</h2><div className="crmMiniRow"><strong>Email</strong><span>{authUser?.email||"—"}</span></div><div className="crmMiniRow"><strong>Joined</strong><span>{authUser?.created_at?new Date(authUser.created_at).toLocaleDateString():new Date(c.created_at).toLocaleDateString()}</span></div><div className="crmMiniRow"><strong>Last sign-in</strong><span>{authUser?.last_sign_in_at?new Date(authUser.last_sign_in_at).toLocaleString():"Not recorded"}</span></div><div className="crmMiniRow"><strong>Email confirmed</strong><span>{authUser?.email_confirmed_at?"Yes":"No"}</span></div></div>
   <div className="panel dashboardPanel"><span className="eyebrow">Internal tracking</span><h2>Admin notes & follow-up</h2><form action="/api/admin/couple-update" method="post" className="formGrid coupleAdminForm"><input type="hidden" name="user_id" value={id}/><div className="field"><label>Account status</label><select name="account_status" defaultValue={c.account_status||"active"}>{statuses.map(s=><option key={s}>{s}</option>)}</select></div><div className="field"><label>Planning stage</label><select name="couple_stage" defaultValue={c.couple_stage||"new"}>{stages.map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select></div><div className="field"><label>First name</label><input name="first_name" defaultValue={c.first_name||""}/></div><div className="field"><label>Partner name</label><input name="partner_name" defaultValue={c.partner_name||""}/></div><div className="field"><label>Wedding date</label><input type="date" name="wedding_date" defaultValue={c.wedding_date?String(c.wedding_date).slice(0,10):""}/></div><div className="field"><label>Last contacted</label><input type="date" name="last_contact_at" defaultValue={c.last_contact_at?String(c.last_contact_at).slice(0,10):""}/></div><div className="field"><label>Next follow-up</label><input type="date" name="next_follow_up_at" defaultValue={c.next_follow_up_at?String(c.next_follow_up_at).slice(0,10):""}/></div><div className="field full"><label>Internal admin notes</label><textarea name="admin_notes" rows={8} defaultValue={c.admin_notes||""} placeholder="Support notes, feedback, outreach history, planning milestones…"/></div><div className="field full"><button className="btn primary">Save Couple Record</button></div></form></div>
  </div></div>
 </div></section></main>
}
