import Link from "next/link";
import {plans} from "../../lib/site";
export const metadata={title:"Vendor Terms of Service | My Portland Wedding"};
export default function VendorTerms(){return <main><section className="pagehero vendorHero"><div className="container narrow"><span className="eyebrow">Vendor legal terms</span><h1>Vendor Terms of Service</h1><p className="meta">Effective September 11, 2026 · Last updated September 11, 2026</p></div></section><section className="section"><article className="container narrow legalPage">
<div className="legalHighlight"><strong>Important recurring billing notice</strong><p>All paid vendor memberships are recurring monthly subscriptions. Your selected membership automatically renews and the authorized payment method is charged each month until canceled in accordance with the cancellation policy below.</p></div>
<p>These Vendor Terms of Service govern paid vendor memberships and vendor use of My Portland Wedding. By purchasing, activating or maintaining a vendor membership, you agree to these Terms.</p>
<h2>1. Memberships</h2><p>Current listing options are Free — $0, Basic — ${plans.basic.price}/month, Pro — ${plans.professional.price}/month, and Premium — ${plans.premium.price}/month. Features are described on the Platform and may be enhanced or modified over time.</p>
<h2>2. Founding Vendor launch promotion</h2><p>For a limited launch promotion, the first five qualifying vendors in each category may receive Premium membership features at the Basic monthly rate and a Founding Vendor badge. Eligibility is determined automatically by category availability at enrollment. The founding rate and badge eligibility remain in effect only while that membership stays continuously active. If the membership is canceled, the founding benefit is permanently forfeited and is not restored if the vendor later rejoins. My Portland Wedding may reject duplicate, fraudulent or category-misclassified accounts intended to improperly obtain a founding position.</p>
<h2>3. Recurring monthly billing</h2><p><strong>All paid vendor memberships automatically renew every month until canceled.</strong> By enrolling, you expressly authorize My Portland Wedding and its payment processor to automatically charge your authorized payment method the applicable membership fee each billing cycle. There is no one-time-payment version of a standard vendor membership unless My Portland Wedding expressly agrees otherwise in writing.</p>
<h2>4. Recurring payment authorization</h2><p>Before billing begins, the Platform displays your selected plan price and recurring terms and requires affirmative acceptance. By completing enrollment, you authorize recurring monthly charges at the disclosed rate and represent that you are authorized to use the payment method provided. If a membership price changes, notice and any additional authorization required by applicable law or payment-network rules will be provided.</p>
<h2 id="cancellation">5. Cancellation policy</h2><div className="legalHighlight"><strong>How to cancel</strong><p>To request cancellation, contact My Portland Wedding by email at <a href="mailto:hello@myportlandwedding.com?subject=Vendor%20Membership%20Cancellation">hello@myportlandwedding.com</a> or by telephone using the customer-service number published by My Portland Wedding. Include your business name and account email so we can identify the membership. We will confirm receipt and processing of your request.</p></div><p>Cancellation stops future recurring charges after the cancellation becomes effective. Except where required by law or expressly agreed otherwise, cancellation does not retroactively refund membership fees already properly charged for a billing period. Vendors should retain their cancellation confirmation. Nothing in this section limits cancellation or refund rights that cannot legally be waived.</p>
<h2>6. Failed payments</h2><p>If a recurring payment fails, My Portland Wedding or its processor may retry the payment as permitted by applicable law and processor rules. Listing benefits may be suspended while an account is past due.</p>
<h2>7. Upgrades and downgrades</h2><p>Vendors may request membership changes. Applicable pricing and benefits may change when the new membership takes effect. Any recurring-charge change will be disclosed as required before the new amount is charged.</p>
<h2>8. Sales-assisted enrollment</h2><p>A representative may create a preliminary vendor account following a sales call, email or other communication. Creating that preliminary account does not itself authorize recurring billing. The vendor must complete the secure enrollment process, review the selected price and recurring terms, provide or authorize a payment method and affirmatively accept recurring-payment authorization before billing begins.</p>
<h2>9. Listings and content</h2><p>Vendors are responsible for accurate business, service, contact, service-area and pricing information. Vendors represent that they own or have permission to use uploaded photographs, logos and marketing materials and grant My Portland Wedding permission to display them in the listing and reasonable promotion of the directory.</p>
<h2>10. Placement, visibility and leads</h2><p>Memberships may include rotating placement, badges, homepage exposure, category positioning or other promotional benefits. No membership guarantees a specific number of impressions, clicks, leads, bookings, sales or revenue. My Portland Wedding may facilitate inquiries but does not guarantee lead quality or purchasing intent.</p>
<h2>11. Vendor conduct</h2><p>Vendors may not knowingly provide false information, impersonate another business, upload content they lack rights to use, manipulate reviews, misuse customer information or use the Platform unlawfully.</p>
<h2>12. Suspension and termination</h2><p>My Portland Wedding may suspend or terminate a listing for fraud, nonpayment, material violations of these Terms, unlawful activity, serious abuse of users or conduct creating material risk to the Platform or its users.</p>
<h2>13. Independent businesses and taxes</h2><p>Vendors remain independent businesses. Nothing creates an employment, agency, franchise, partnership or joint-venture relationship. Vendors remain responsible for their own taxes and obligations arising from services they provide.</p>
<h2>14. Changes and governing law</h2><p>My Portland Wedding may update these Terms and membership pricing. Notice will be provided where required. These Vendor Terms are governed by Oregon law except where applicable law requires otherwise.</p>
<h2>15. Contact</h2><p>Billing questions and cancellation requests may be sent to <a href="mailto:hello@myportlandwedding.com">hello@myportlandwedding.com</a> or made by telephone using the customer-service number published by My Portland Wedding.</p>
<p className="legalNote">These Vendor Terms supplement the <Link href="/terms-of-use">Terms of Use</Link>. Our handling of personal information is described in the <Link href="/privacy-policy">Privacy Policy</Link>.</p>
</article></section></main>}
