import WeddingBuilder from "../../components/WeddingBuilder";
import { createSupabaseServerClient } from "../../lib/supabase/server";
export const dynamic="force-dynamic";
export const metadata={title:"Wedding Builder by My Portland Wedding",description:"Build a personalized Portland wedding plan from your budget, guest count, style and priorities, then discover local vendors that fit.",alternates:{canonical:"/wedding-builder"},openGraph:{url:"/wedding-builder",images:[{url:"/brand/mpw-social-share.png",width:1200,height:630,alt:"Wedding Builder by My Portland Wedding"}]}};
export default async function WeddingBuilderPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){
 const params=await searchParams;
 const budget=Math.min(250000,Math.max(5000,Number(params.budget)||30000));
 const guests=Math.min(1000,Math.max(10,Number(params.guests)||100));
 const city=typeof params.city==="string"?params.city:"Portland";
 const date=typeof params.date==="string"?params.date:"";
 const style=typeof params.style==="string"?params.style:"";
 const hasStarter=Boolean(params.budget||params.guests||params.city||params.date||params.style);
 const db=await createSupabaseServerClient();
 const {data:{user}}=await db.auth.getUser();
 const {data:adminUser}=user?await db.from("admin_users").select("user_id").eq("user_id",user.id).maybeSingle():{data:null};
 const suppressVendorSignals=Boolean(adminUser);
 const {data}=await db.from("vendor_profiles").select("id,slug,business_name,primary_category,secondary_categories,city,service_cities,pricing_from,pricing_typical,pricing_max,pricing_packages,wedding_styles,guest_capacity_min,guest_capacity_max,availability_status,unavailable_dates,vendor_attributes,plan,rating,description,founding_vendor,listing_state").eq("market_slug","portland").eq("status","active").neq("listing_state","unclaimed").limit(1000);
 const vendorIds=(data||[]).map((v:any)=>v.id);
 const {data:photos}=vendorIds.length?await db.from("vendor_photos").select("vendor_id,storage_path,sort_order").in("vendor_id",vendorIds).order("sort_order",{ascending:true}):{data:[] as any[]};
 const firstPhoto=new Map<string,string>();(photos||[]).forEach((p:any)=>{if(!firstPhoto.has(p.vendor_id))firstPhoto.set(p.vendor_id,`${process.env.NEXT_PUBLIC_SUPABASE_URL}/storage/v1/object/public/vendor-media/${p.storage_path}`)});
 const builderVendors=(data||[]).map((v:any)=>({...v,photo_url:firstPhoto.get(v.id)||null}));
 return <main className="weddingBuilderPage wbProductPage"><section className="wbProductMast"><div className="wbProductMastInner"><div className="wbProductIdentity"><img src="/brand/mpw-master-logo.png" alt="My Portland Wedding — Plan Local. Love Always."/><div><span>MY PORTLAND WEDDING PRESENTS</span><strong>Wedding Builder</strong><em>Plan Local. Love Always.</em></div></div><div className="wbProductPromise"><span className="wbProductEdition">YOUR PERSONAL WEDDING BLUEPRINT · PORTLAND EDITION</span><h1>This is where your wedding starts feeling like yours.</h1><p>A playful, personalized planning experience that turns what you love, what matters and what you want to spend into a wedding blueprint built around you.</p><div className="wbProductSignals"><span>✦ Personalized matching</span><span>♥ Local vendor team</span><span>↗ Interactive budget</span><span>✂ Smart DIY options</span></div></div><div className="wbProductStamp" aria-hidden="true"><span>BUILT</span><strong>FOR</strong><span>YOUR</span><em>DAY</em></div></div></section><section className="wbStudioSection"><div className="wbStudioFrame"><aside className="wbStudioRail" aria-label="Wedding Builder journey"><div className="wbStudioRailBrand"><small>WEDDING BUILDER</small><strong>Your Wedding Journey</strong></div><ol><li className="active"><b>01</b><span>Basics<small>Set the scene</small></span></li><li><b>02</b><span>Vibe<small>Find your feeling</small></span></li><li><b>03</b><span>Celebration<small>Shape the party</small></span></li><li><b>04</b><span>Priorities<small>Choose what matters</small></span></li><li><b>05</b><span>Blueprint<small>Meet your wedding</small></span></li></ol><div className="wbStudioRailNote"><span>✦</span><p>Nothing here is one-size-fits-all. Your answers reshape the plan as you go.</p></div></aside><div className="wbStudioWorkspace"><WeddingBuilder vendors={builderVendors as any} initialAnswers={hasStarter?{budget,guests,city,date,style}:undefined} suppressVendorSignals={suppressVendorSignals}/></div></div></section></main>
}