import Link from "next/link";
import { planningChecklists } from "../../lib/content";
export const metadata = {
  title: 'Free Wedding Planning Tools for Portland Couples',
  description: 'Use free wedding planning tools for budgets, guest lists, timelines, checklists and Wedding Builder by My Portland Wedding.',
  alternates: { canonical: '/planning-tools' },
  openGraph: { title: 'Free Wedding Planning Tools for Portland Couples', description: 'Use free wedding planning tools for budgets, guest lists, timelines, checklists and Wedding Builder by My Portland Wedding.', url: '/planning-tools', images: [{ url: '/brand/mpw-social-share.png', width: 1200, height: 630, alt: 'My Portland Wedding — Plan Local. Love Always.' }] }
};

export default function Page(){return <main>
<section className="pagehero planningToolsHero"><div className="container"><span className="eyebrow">Plan with less stress</span><h1>Wedding Planning Tools</h1><p className="meta">Free planning tools, checklists and organizers made for Portland couples. Keep the details in one place and make the next step feel manageable.</p></div></section>
<section className="section"><div className="container"><div className="sectionTitle"><span className="eyebrow">Your interactive planners</span><h2>Plan your wedding, one step at a time.</h2><p className="meta sectionIntro">Use the interactive planners for your budget, guest list and wedding-day timeline, then explore Wedding Builder when you’re ready for a personalized local vendor plan.</p></div><div className="featuredTools"><Link href="/wedding-builder" className="featureTool budgetFeature"><span className="featureToolIcon">♡</span><div><span className="eyebrow">Interactive</span><h2>Wedding Builder by My Portland Wedding</h2><p>Tell us your budget, guest count and priorities. Get a personalized wedding blueprint and local vendor matches.</p><span className="textLink">Build my wedding →</span></div></Link><Link href="/planning-tools/budget-calculator" className="featureTool budgetFeature"><span className="featureToolIcon">$</span><div><span className="eyebrow">Budget</span><h2>Wedding Budget Calculator</h2><p>Track estimates, signed contracts, payments and what is still outstanding.</p><span className="textLink">Open budget planner →</span></div></Link><Link href="/planning-tools/guest-list" className="featureTool guestFeature"><span className="featureToolIcon">✉</span><div><span className="eyebrow">Guests</span><h2>Guest List & RSVP Tracker</h2><p>Organize households, party sizes, RSVPs, meal choices, groups and tables.</p><span className="textLink">Open guest manager →</span></div></Link><Link href="/planning-tools/timeline" className="featureTool guestFeature"><span className="featureToolIcon">⏱</span><div><span className="eyebrow">Wedding day</span><h2>My Wedding Timeline</h2><p>Start simple. As your vendor team comes together, your timeline gets more personal.</p><span className="textLink">Open my timeline →</span></div></Link></div><div className="sectionTitle checklistTitle"><span className="eyebrow">Start checking things off</span><h2>Your checklist library.</h2><p className="meta sectionIntro">Open any checklist, mark items complete and your progress stays saved on this device.</p></div><div className="toolGrid">{planningChecklists.map((tool,i)=><Link href={`/planning-tools/${tool.slug}`} className="toolCard" key={tool.slug}><span className="toolNumber">{String(i+1).padStart(2,"0")}</span><span className="eyebrow">{tool.eyebrow}</span><h2>{tool.title}</h2><p>{tool.intro}</p><span className="textLink">Open checklist →</span></Link>)}</div></div></section>
<section className="section sageSection"><div className="container planningAdvice"><div><span className="eyebrow">Planning tip</span><h2>Start with what matters most today.</h2></div><p className="meta">Start with the master checklist, then use the focused lists when you are touring venues, hiring vendors, finalizing the budget or heading into wedding week.</p></div></section>
</main>}
