import {NextResponse} from "next/server";
import {createSupabaseServerClient} from "../../../../lib/supabase/server";

const MPW=/my\s*portland\s*wedding|myportlandwedding\.com|mpw-(?:listed|supported|professional|premium|founding)-vendor/i;
function normalize(v?:string|null){if(!v)return null;try{return new URL(/^https?:\/\//i.test(v)?v:`https://${v}`).toString()}catch{return null}}
async function fetchPage(url:string){const c=new AbortController();const t=setTimeout(()=>c.abort(),7000);try{const r=await fetch(url,{redirect:"follow",signal:c.signal,headers:{"user-agent":"Mozilla/5.0 (compatible; MPWBadgeChecker/1.0; +https://www.myportlandwedding.com)"},cache:"no-store"});const type=r.headers.get("content-type")||"";if(!r.ok||!type.includes("text/html"))return {ok:false,status:r.status,html:"",final:r.url};const html=(await r.text()).slice(0,1500000);return {ok:true,status:r.status,html,final:r.url}}catch{return {ok:false,status:0,html:"",final:url}}finally{clearTimeout(t)}}
function evidence(html:string){if(/myportlandwedding\.com/i.test(html))return "MPW backlink detected";if(/mpw-(?:listed|supported|professional|premium|founding)-vendor/i.test(html))return "MPW badge asset detected";if(/my\s*portland\s*wedding/i.test(html))return "My Portland Wedding mention detected";return ""}
export async function POST(req:Request){const supabase=await createSupabaseServerClient();const {data:{user}}=await supabase.auth.getUser();if(!user)return NextResponse.json({error:"Unauthorized"},{status:401});const {data:admin}=await supabase.from("admin_users").select("user_id").eq("user_id",user.id).maybeSingle();if(!admin)return NextResponse.json({error:"Admin access required"},{status:403});const {vendor_id}=await req.json();const {data:v}=await supabase.from("vendor_profiles").select("id,website,instagram,facebook,tiktok,pinterest,youtube").eq("id",vendor_id).maybeSingle();if(!v)return NextResponse.json({error:"Vendor not found"},{status:404});
 const results:any[]=[];const website=normalize(v.website);if(website){const origin=new URL(website).origin;const queue=[website];const seen=new Set<string>();let found=false;while(queue.length&&seen.size<12&&!found){const u=queue.shift()!;if(seen.has(u))continue;seen.add(u);const p=await fetchPage(u);if(!p.ok){if(seen.size===1)results.push({url:u,type:"Website",status:"unverified",evidence:p.status?`Website returned HTTP ${p.status}`:"Website blocked or timed out"});continue}const ev=evidence(p.html);if(MPW.test(p.html)){results.push({url:p.final,type:"Website",status:"detected",evidence:ev});found=true;break}for(const m of p.html.matchAll(/href=["']([^"'#]+)["']/gi)){try{const n=new URL(m[1],origin);if(n.origin===origin&&!seen.has(n.toString())&&queue.length<25)queue.push(n.toString())}catch{}}}if(!found&&!results.some(x=>x.type==="Website"))results.push({url:website,type:"Website",status:"not_detected",evidence:`Checked ${seen.size} public page${seen.size===1?"":"s"}`})}else results.push({url:"/admin/vendors/"+vendor_id,type:"Website",status:"not_configured",evidence:"No website URL saved"});
 for(const [type,val] of [["Instagram",v.instagram],["Facebook",v.facebook],["TikTok",v.tiktok],["Pinterest",v.pinterest],["YouTube",v.youtube]] as any[]){const u=normalize(val);if(!u)continue;const p=await fetchPage(u);if(p.ok&&MPW.test(p.html))results.push({url:u,type,status:"detected",evidence:evidence(p.html)});else results.push({url:u,type,status:p.ok?"not_detected":"unverified",evidence:p.ok?"No MPW reference detected on the public HTML returned":"Platform blocked or limited automated verification"})}
 const detected=results.filter(x=>x.status==="detected").length, verify=results.filter(x=>x.status==="unverified").length;return NextResponse.json({status:detected?"detected":verify?"partial":"not_detected",summary:detected?`MPW presence detected in ${detected} location${detected===1?"":"s"}.`:verify?"No confirmed MPW presence yet; some locations could not be verified automatically.":"No MPW badge, backlink or mention was detected in the checked locations.",checkedAt:new Date().toISOString(),locations:results})}
