import Link from "next/link";
export const metadata={title:"Privacy Policy | My Portland Wedding"};
export default function PrivacyPolicy(){return <main><section className="pagehero"><div className="container narrow"><span className="eyebrow">Your privacy</span><h1>Privacy Policy</h1><p className="meta">Effective September 11, 2026 · Last updated September 11, 2026</p></div></section><section className="section"><article className="container narrow legalPage">
<p>This Privacy Policy describes how My Portland Wedding collects, uses, stores and shares information when people use our website and related services.</p>
<h2>1. Information we collect</h2><p>Depending on your use of the Platform, we may collect names, email addresses, telephone numbers, account credentials, wedding dates, planning information, saved vendors, guest-list and budget information, inquiries, reviews, vendor business information, service areas, listing materials, subscription and billing status, and device, browser, IP-address and usage information.</p>
<h2>2. Payment information</h2><p>Vendor payments are processed through a third-party payment processor. My Portland Wedding is designed to use processor-provided secure payment technology or tokenization rather than storing complete payment-card numbers in the application database. The payment processor may separately collect and process payment information under its own privacy and security practices.</p>
<h2>3. How we use information</h2><p>We may use information to operate accounts, display listings, provide planning tools, save preferences, process memberships, facilitate inquiries, administer reviews, provide customer service, prevent fraud or abuse, improve and secure the Platform, analyze performance, send important account and transactional communications, and comply with legal obligations.</p>
<h2>4. Vendor inquiries</h2><p>When a couple submits an inquiry to a vendor, information entered in that inquiry is shared with the selected vendor so the vendor can respond. Independent vendors may then process that information under their own privacy practices.</p>
<h2>5. Planning and guest information</h2><p>Couples may choose to store personal wedding-planning information. Users should avoid entering sensitive information that is unnecessary for wedding planning. We do not sell a couple’s private guest list to wedding vendors.</p>
<h2>6. How information may be shared</h2><p>We may share information with service providers reasonably necessary to operate the Platform, including hosting, database, email, analytics, security and payment-processing providers. We may also disclose information when reasonably necessary to comply with law, enforce agreements, investigate fraud or security incidents, protect users, or facilitate a business transaction such as a merger or acquisition.</p>
<h2>7. Sale of personal information</h2><p>My Portland Wedding does not intend to sell personal information to unrelated third parties for monetary compensation. Paid vendor placement does not give vendors unrestricted access to private user-account information.</p>
<h2>8. Cookies and similar technologies</h2><p>The Platform may use cookies, local storage, sessions, analytics tools and similar technologies to maintain sessions, remember preferences, measure usage, improve performance and provide functionality.</p>
<h2>9. Security</h2><p>We use reasonable administrative and technical measures designed to protect information. No internet-connected system can guarantee absolute security. Users are responsible for protecting passwords and account credentials.</p>
<h2>10. Retention</h2><p>We retain personal information for as long as reasonably necessary to operate the Platform, provide requested services, maintain appropriate business and transaction records, resolve disputes, enforce agreements and satisfy legal obligations. Retention periods vary by information type.</p>
<h2>11. Your choices and requests</h2><p>Users may update certain account information through available account features and may contact us regarding privacy questions or requests concerning their information. Certain records may be retained for legitimate security, fraud-prevention, tax, payment, contractual or legal purposes even after an account is closed.</p>
<h2>12. Communications</h2><p>We may send transactional communications concerning accounts, inquiries, subscriptions, security, payments and other Platform activity. Where required, promotional emails will include an appropriate method to unsubscribe. Opting out of marketing does not prevent transactional or legally required communications.</p>
<h2>13. Children</h2><p>My Portland Wedding is not intended for children under 13, and we do not knowingly solicit personal information from children under 13.</p>
<h2>14. Third-party sites</h2><p>The Platform may link to independent third-party websites. My Portland Wedding is not responsible for their content or privacy practices.</p>
<h2>15. Changes to this policy</h2><p>We may update this Privacy Policy to reflect changes to the Platform, practices, service providers or applicable requirements. The current version will display its effective or last-updated date.</p>
<h2>16. Contact</h2><p>Privacy questions or requests may be sent to <a href="mailto:hello@myportlandwedding.com">hello@myportlandwedding.com</a>.</p>
<p className="legalNote">Consumers should also review our <Link href="/consumer-terms">Consumer Terms of Service</Link>. See our <Link href="/terms-of-use">Terms of Use</Link> and <Link href="/vendor-terms">Vendor Terms of Service</Link>.</p>
</article></section></main>}
