import {NextResponse} from "next/server";
import {createSupabaseServerClient} from "../../../../lib/supabase/server";
import {createAdminClient} from "../../../../lib/supabase/admin";
import {sendEmailOnce,escapeHtml,siteUrl} from "../../../../lib/email";

const badgeKey=(plan:string,founding?:boolean)=>founding?"founding":plan==="free"?"listed":plan==="basic"?"supported":plan==="professional"?"professional":"premium";
const badgeLabel=(key:string)=>({listed:"Listed Vendor",supported:"Supported Vendor",professional:"Professional Vendor",premium:"Premium Vendor",founding:"Founding Vendor"} as Record<string,string>)[key]||"Vendor";
export async function POST(req:Request){
 const supabase=await createSupabaseServerClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user)return NextResponse.json({error:"Unauthorized"},{status:401});
 const {data:admin}=await supabase.from("admin_users").select("user_id").eq("user_id",user.id).maybeSingle(); if(!admin)return NextResponse.json({error:"Admin access required"},{status:403});
 const body=await req.json().catch(()=>({})); const ids=Array.isArray(body.vendor_ids)?body.vendor_ids.slice(0,150):[]; if(!ids.length)return NextResponse.json({error:"No vendors selected"},{status:400});
 const db=createAdminClient(); const {data:vendors}=await db.from("vendor_profiles").select("id,business_name,email,plan,founding_vendor,slug").in("id",ids);
 let sent=0, skipped=0, failed=0;
 for(const v of vendors||[]){
  if(!v.email){skipped++;continue} const key=badgeKey(v.plan,Boolean(v.founding_vendor)), label=badgeLabel(key); const profile=`${siteUrl}/vendor/${v.slug}`; const dash=`${siteUrl}/vendor/dashboard#badges`; const base=`${siteUrl}/badges/mpw-${key}-vendor`;
  const badgeImage=`https://www.myportlandwedding.com/badges/mpw-${key}-vendor.png`;
  const html=`<div style="text-align:center;margin:4px 0 24px"><div style="font-size:14px;letter-spacing:.4px;color:#8b6f68;margin-bottom:8px">Plan Local. Love Always.</div><h2 style="font-family:Georgia,serif;font-size:23px;line-height:1.3;margin:0;color:#302b2b">Show couples you’re part of the<br/>My Portland Wedding community.</h2></div><p>Hi ${escapeHtml(v.business_name||"there")},</p><p>Your official <strong>My Portland Wedding ${label}</strong> badge is ready! Add it to your website to show couples you’re a recognized local MPW vendor — and your badge automatically links them to your MPW profile.</p><div style="text-align:center;margin:26px 0"><a href="${profile}" style="text-decoration:none"><img src="${badgeImage}" width="300" alt="My Portland Wedding ${label} badge" style="display:inline-block;width:100%;max-width:300px;height:auto;border:0"/></a></div><div style="text-align:center;margin:8px 0 26px"><a href="${dash}" style="display:inline-block;background:#b65f5b;color:white;text-decoration:none;padding:14px 24px;border-radius:999px;font-weight:700">Add My Badge to My Website</a></div><div style="background:#fbf7f3;border:1px solid #eadfd8;border-radius:16px;padding:18px 20px;margin:24px 0"><strong style="display:block;margin-bottom:8px">No backlink setup required.</strong><div style="line-height:1.6;color:#514948">Click <strong>Add My Badge to My Website</strong>, choose Wix, Squarespace, WordPress, Showit, GoDaddy, Shopify or Other, and MPW will give you simple instructions. Your linked badge is already prepared for your specific MPW profile.</div></div><div style="border-top:1px solid #eadfd8;margin-top:26px;padding-top:18px;text-align:center;font-size:13px;color:#837874"><strong>Using your badge on social media or marketing materials?</strong><br/>Image downloads are available from your badge dashboard. For your website, use the linked badge above so couples can click directly to your MPW profile.</div><p style="font-size:14px;line-height:1.6;color:#514948"><strong>Already added it?</strong> Great! We’ll automatically look for your public badge, backlink or My Portland Wedding mention during our next vendor scan.</p><p style="font-size:14px;line-height:1.6;color:#514948">Your MPW profile: <a href="${profile}" style="color:#5f6f61">${profile}</a></p>`;
  const result=await sendEmailOnce({eventKey:`badge_package:${v.id}:${new Date().toISOString().slice(0,10)}`,to:v.email,subject:`Your My Portland Wedding ${label} badge package`,title:"Your MPW Vendor Badge Package",body:html});
  if(result.sent){sent++;await db.from("analytics_events").insert({market_slug:"portland",vendor_id:v.id,event_type:"badge_pack_sent"})} else if(result.reason==="already_sent"){skipped++} else failed++;
 }
 return NextResponse.json({sent,skipped,failed,total:(vendors||[]).length});
}
