import Link from "next/link";
import VendorTierBadge from "../components/VendorTierBadge";
import { createSupabaseServerClient } from "../lib/supabase/server";
import { decodeDisplayText } from "../lib/text";
import HomeWeddingBuilder from "../components/HomeWeddingBuilder";
import type { Metadata } from "next";
export const metadata:Metadata={title:"Portland Wedding Planner & Local Vendors",description:"Build your Portland wedding with Wedding Builder, local wedding pros, intelligent budgets and planning tools from My Portland Wedding.",alternates:{canonical:"/"}};
function photoUrl(path?:string|null){return path&&process.env.NEXT_PUBLIC_SUPABASE_URL?`${process.env.NEXT_PUBLIC_SUPABASE_URL}/storage/v1/object/public/vendor-media/${path}`:null}
const cats=[["venues","Venues","Where it all happens"],["photography","Photography","Proof it happened"],["planners","Planners","Professional calm"],["florists","Florals","A reasonable amount of flowers"],["catering","Food + Drink","Feed everybody"],["djs","Music","Absolutely play the song"]] as const;
export default async function Home(){const supabase=await createSupabaseServerClient();const {data:premium}=await supabase.from("vendor_profiles").select("id,slug,business_name,primary_category,city,rating,plan,founding_vendor,vendor_photos(storage_path,sort_order)").eq("market_slug","portland").eq("status","active").eq("plan","premium").limit(100);const withImages=(premium||[]).filter((v:any)=>(v.vendor_photos||[]).some((p:any)=>Boolean(String(p?.storage_path||"").trim())));const featured=withImages.sort(()=>Math.random()-.5).slice(0,6);const mini=featured.slice(0,3).map((v:any)=>{const ph=(v.vendor_photos||[]).sort((a:any,b:any)=>(a.sort_order||0)-(b.sort_order||0));return {slug:v.slug,business_name:decodeDisplayText(v.business_name),photo_url:photoUrl(ph[0]?.storage_path)}});return <main className="nocturneHome">
<section className="nocturneHero"><div className="nocturneHeroCopy"><div className="nocturneSeal"><img src="/brand/mpw-heart-sprig-clean.png" alt=""/><span>MY PORTLAND WEDDING</span></div><p className="nocturneKicker">PORTLAND'S WEDDING PLANNING PLAYGROUND</p><h1>Plan the<br/><em>heck yes.</em></h1><p className="nocturneDeck">The budget. The vibe. The flowers. The people. The wildly specific thing you saw at 1:14 a.m. Put it all here and build a wedding that actually feels like yours.</p><div className="nocturneActions"><Link href="/wedding-builder">Build my wedding <b>↗</b></Link><Link href="/vendors">Find my people</Link></div><div className="nocturneNotes"><span>FREE FOR COUPLES</span><span>LOCAL PORTLAND PROS</span><span>ZERO BEIGE PERSONALITY</span></div></div><div className="nocturneBuilder"><div className="nocturneBuilderLabel"><span>THE MAIN EVENT</span><b>Wedding Builder</b><i>♡</i></div><HomeWeddingBuilder featured={mini}/></div></section>
<section className="nocturneVendors"><header><div><span>FEATURED RIGHT NOW</span><h2>Meet the people<br/>who make <em>magic.</em></h2></div><Link href="/vendors">Browse every local pro →</Link></header><div className="nocturneVendorRail">{featured.slice(0,4).map((v:any,i:number)=>{const ph=(v.vendor_photos||[]).sort((a:any,b:any)=>(a.sort_order||0)-(b.sort_order||0));const src=photoUrl(ph[0]?.storage_path);return <Link href={`/vendor/${v.slug}`} className="nocturneVendor" key={v.id}><div className="nocturneVendorPhoto">{src&&<img src={src} alt={`${decodeDisplayText(v.business_name)} wedding work`}/>}<span>0{i+1}</span></div><div className="nocturneVendorInfo"><VendorTierBadge plan={v.plan} foundingVendor={v.founding_vendor}/><h3>{decodeDisplayText(v.business_name)}</h3><p>{decodeDisplayText(v.primary_category||"Wedding Pro")} · {decodeDisplayText(v.city||"Portland")}</p><small>★ {v.rating||"5.0"} · Portland favorite</small></div></Link>})}</div></section>
<section className="nocturneStatement"><span>NOT A DIRECTORY.</span><h2>A wedding plan<br/>with a <em>pulse.</em></h2><p>Wedding Builder turns your budget, guest count, priorities and taste into a living plan—then brings local vendors into the decisions where they actually belong.</p><Link href="/wedding-builder">Show me what mine looks like →</Link></section>
<section className="nocturneCategories"><div className="nocturneCatIntro"><span>CHOOSE YOUR CHARACTERS</span><h2>The dream team.</h2><p>Start with whoever you're currently obsessing over.</p></div><div className="nocturneCatList">{cats.map(([slug,label,note],i)=><Link href={`/vendors/${slug}`} key={slug}><b>{String(i+1).padStart(2,"0")}</b><strong>{label}</strong><span>{note}</span><i>↗</i></Link>)}</div></section>
<section className="nocturneBrain mpwBrainCompact"><div className="mpwBrainIntro"><span>BEAUTIFUL BRAINS</span><h2>Change one thing.<br/><em>See the whole plan react.</em></h2><p>Wedding Builder keeps your budget, guest count and Portland vendor team connected.</p><Link href="/wedding-builder">Open Wedding Builder ↗</Link></div><div className="mpwLabPreview mpwLabStrip"><div className="mpwLabStripHead"><span>⚡ WEDDING LAB</span><strong>What if your guest list changed?</strong><p>Try it before you commit.</p></div><div className="mpwLabStripBody"><div className="mpwLabStripInput"><button type="button">−10</button><b>100 guests</b><button type="button">+10</button></div><div className="mpwLabStripArrow">→</div><div className="mpwLabStripResult"><small>LIVE PLAN</small><strong>$30,000</strong><span>Right on plan</span></div><div className="mpwLabStripNote">Budget, vendors and priorities recalculate together.</div></div></div></section>
<section className="nocturneClose"><img src="/brand/mpw-heart-sprig-clean.png" alt=""/><p>PLAN LOCAL. LOVE ALWAYS.</p><h2>Okay.<br/><em>Let's get you married.</em></h2><Link href="/wedding-builder">Build my wedding — free ↗</Link></section>
</main>}
