"use client";
import { useMemo, useState } from "react";

type Item={id:string;category:string;budgeted:number;actual:number;paid:number;notes?:string|null;sort_order?:number};
const starter=["Venue","Catering","Bar","Photography","Videography","Planning / Coordination","Florals & Design","Music / Entertainment","Attire","Beauty","Cake & Desserts","Rentals & Lighting","Stationery","Transportation","Officiant & License","Tips & Miscellaneous"];
export default function BudgetCalculator({initialItems}:{initialItems:Item[]}){
 const [items,setItems]=useState<Item[]>(initialItems); const [error,setError]=useState(""); const [previewNotice,setPreviewNotice]=useState("");
 const totals=useMemo(()=>items.reduce((a,x)=>({budgeted:a.budgeted+Number(x.budgeted||0),actual:a.actual+Number(x.actual||0),paid:a.paid+Number(x.paid||0)}),{budgeted:0,actual:0,paid:0}),[items]);
 async function save(item:Item){const r=await fetch("/api/couple/budget",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(item)}); const j=await r.json(); if(!r.ok){setError(j.error||"Could not save");return;} if(j.preview){setPreviewNotice("Preview mode: budget changes are simulated and were not saved.");return;} setItems(x=>x.map(y=>y.id===item.id?j.item:y));}
 async function add(category="New category"){const temp={id:`temp-${Date.now()}`,category,budgeted:0,actual:0,paid:0,notes:""}; const r=await fetch("/api/couple/budget",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...temp,id:undefined})}); const j=await r.json(); if(r.ok&&j.preview){setPreviewNotice("Preview mode: budget changes are simulated and were not saved.");return;} if(r.ok)setItems(x=>[...x,j.item]); else setError(j.error||"Could not add");}
 async function remove(id:string){const r=await fetch("/api/couple/budget",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});const j=await r.json().catch(()=>({}));if(j.preview){setPreviewNotice("Preview mode: budget changes are simulated and were not saved.");return;}if(r.ok)setItems(x=>x.filter(y=>y.id!==id));else setError(j.error||"Could not remove");}
 async function seed(){for(const c of starter.filter(c=>!items.some(i=>i.category===c))) await add(c);}
 function patch(id:string,key:keyof Item,value:any){setItems(x=>x.map(i=>i.id===id?{...i,[key]:value}:i));}
 return <div className="plannerApp"><div className="connectedToolNudge"><span>✨</span><div><strong>Want us to build with this?</strong><p>Wedding Builder can turn your planned total into a realistic local vendor lineup.</p></div><a className="btn light" href={`/wedding-builder?budget=${Math.max(5000,Math.round(totals.budgeted||30000))}`}>Build with this budget →</a></div><div className="plannerSummary"><div><span>Planned</span><strong>${totals.budgeted.toLocaleString()}</strong></div><div><span>Actual</span><strong>${totals.actual.toLocaleString()}</strong></div><div><span>Paid</span><strong>${totals.paid.toLocaleString()}</strong></div><div><span>Remaining</span><strong>${Math.max(0,totals.actual-totals.paid).toLocaleString()}</strong></div></div>{previewNotice&&<div className="notice success">{previewNotice}</div>}{error&&<div className="notice error">{error}</div>}<div className="plannerActions"><button className="btn primary" onClick={()=>add()}>+ Add category</button><button className="btn light" onClick={seed}>Add common wedding categories</button></div><div className="budgetTableWrap"><table className="budgetTable"><thead><tr><th>Category</th><th>Budgeted</th><th>Actual</th><th>Paid</th><th>Notes</th><th></th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td><input value={i.category} onChange={e=>patch(i.id,"category",e.target.value)} onBlur={()=>save(i)}/></td><td><input type="number" min="0" value={i.budgeted} onChange={e=>patch(i.id,"budgeted",Number(e.target.value))} onBlur={()=>save(i)}/></td><td><input type="number" min="0" value={i.actual} onChange={e=>patch(i.id,"actual",Number(e.target.value))} onBlur={()=>save(i)}/></td><td><input type="number" min="0" value={i.paid} onChange={e=>patch(i.id,"paid",Number(e.target.value))} onBlur={()=>save(i)}/></td><td><input value={i.notes||""} onChange={e=>patch(i.id,"notes",e.target.value)} onBlur={()=>save(i)}/></td><td><button className="iconDelete" onClick={()=>remove(i.id)} aria-label="Remove">×</button></td></tr>)}</tbody></table></div></div>
}
