"use client";
import { useMemo, useState } from "react";
type Guest={id:string;name:string;email?:string|null;party_size:number;rsvp_status:string;meal_choice?:string|null;group_name?:string|null;table_name?:string|null;notes?:string|null};
const blank={name:"",email:"",party_size:1,rsvp_status:"pending",meal_choice:"",group_name:"",table_name:"",notes:""};
export default function GuestListManager({initialGuests}:{initialGuests:Guest[]}){
 const [guests,setGuests]=useState<Guest[]>(initialGuests); const [form,setForm]=useState<any>(blank); const [error,setError]=useState("");
 const counts=useMemo(()=>guests.reduce((a,g)=>{const n=Number(g.party_size||1);a.total+=n;if(g.rsvp_status==="yes")a.yes+=n;if(g.rsvp_status==="no")a.no+=n;else if(g.rsvp_status==="pending")a.pending+=n;return a},{total:0,yes:0,no:0,pending:0}),[guests]);
 async function add(e:any){e.preventDefault();const r=await fetch("/api/couple/guests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const j=await r.json();if(!r.ok){setError(j.error||"Could not add guest");return;}setGuests(x=>[j.guest,...x]);setForm(blank);}
 async function update(g:Guest,patch:any){const next={...g,...patch};setGuests(x=>x.map(y=>y.id===g.id?next:y));const r=await fetch("/api/couple/guests",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(next)});if(!r.ok)setError("Could not save guest change");}
 async function remove(id:string){await fetch("/api/couple/guests",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id})});setGuests(x=>x.filter(g=>g.id!==id));}
 return <div className="plannerApp"><div className="connectedToolNudge"><span>💌</span><div><strong>{counts.total?`${counts.total} guests changes the plan—in a useful way.`:"Guest count helps us make smarter matches."}</strong><p>Send your current guest count to Wedding Builder so venue capacity and budget estimates fit your wedding.</p></div><a className="btn light" href={`/wedding-builder?guests=${Math.max(10,counts.total||100)}`}>Update my wedding →</a></div><div className="plannerSummary"><div><span>Invited</span><strong>{counts.total}</strong></div><div><span>Attending</span><strong>{counts.yes}</strong></div><div><span>Pending</span><strong>{counts.pending}</strong></div><div><span>Declined</span><strong>{counts.no}</strong></div></div>{error&&<div className="notice error">{error}</div>}<form className="guestQuickAdd" onSubmit={add}><input placeholder="Guest or household name" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><input type="email" placeholder="Email (optional)" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input type="number" min="1" max="20" value={form.party_size} onChange={e=>setForm({...form,party_size:Number(e.target.value)})}/><button className="btn primary">+ Add guest</button></form><div className="guestCards">{guests.map(g=><div className="guestCard" key={g.id}><div className="guestCardTop"><div><strong>{g.name}</strong><span>{g.email||"No email added"}</span></div><button className="iconDelete" onClick={()=>remove(g.id)}>×</button></div><div className="guestFields"><label>Party size<input type="number" min="1" max="20" value={g.party_size} onChange={e=>update(g,{party_size:Number(e.target.value)})}/></label><label>RSVP<select value={g.rsvp_status} onChange={e=>update(g,{rsvp_status:e.target.value})}><option value="pending">Pending</option><option value="yes">Attending</option><option value="no">Declined</option></select></label><label>Group<input value={g.group_name||""} onChange={e=>update(g,{group_name:e.target.value})} placeholder="Family, Friends..."/></label><label>Table<input value={g.table_name||""} onChange={e=>update(g,{table_name:e.target.value})} placeholder="Table 4"/></label><label>Meal<input value={g.meal_choice||""} onChange={e=>update(g,{meal_choice:e.target.value})} placeholder="Entrée choice"/></label><label>Notes<input value={g.notes||""} onChange={e=>update(g,{notes:e.target.value})} placeholder="Allergy, plus-one..."/></label></div></div>)}</div></div>
}
