"use client";
import { useEffect,useState } from "react";
type Check={id:string;group:string;name:string;status:"pass"|"warning"|"failed";detail:string;fix:string;url?:string;autoFix?:boolean};
type Scan={scanVersion:string;site:string;startedAt:string;finishedAt:string;durationMs:number;totals:{pass:number;warning:number;failed:number};summary:any;checks:Check[]};
const key="mpw-site-health-history-v1";
export default function SiteHealthScanner(){
 const [scan,setScan]=useState<Scan|null>(null),[running,setRunning]=useState(false),[fixing,setFixing]=useState(false),[error,setError]=useState(""),[fixMessage,setFixMessage]=useState(""),[history,setHistory]=useState<Scan[]>([]),[filter,setFilter]=useState("all");
 useEffect(()=>{try{setHistory(JSON.parse(localStorage.getItem(key)||"[]"))}catch{}},[]);
 async function run(){setRunning(true);setError("");try{const r=await fetch("/api/admin/site-health",{method:"POST"});const data=await r.json();if(!r.ok)throw new Error(data.error||"Scan failed");setScan(data);const next=[data,...history].slice(0,12);setHistory(next);localStorage.setItem(key,JSON.stringify(next));}catch(e:any){setError(e.message||"Scan failed")}finally{setRunning(false)}}
 async function autoFix(){if(!scan)return;setFixing(true);setError("");setFixMessage("");try{const candidates=scan.checks.filter(c=>c.status!=="pass"&&c.autoFix);if(!candidates.length){setFixMessage("No safe automatic fixes are available for this scan. Issues that require source code, Vercel settings, credentials, billing, or destructive data changes are never changed automatically.");return;}const r=await fetch("/api/admin/site-health/auto-fix",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({checks:candidates})});const data=await r.json();if(!r.ok)throw new Error(data.error||"Auto Fix failed");setFixMessage(data.message||"Auto Fix completed.");if(data.fixed?.length)await run();}catch(e:any){setError(e.message||"Auto Fix failed")}finally{setFixing(false)}}
 function download(format:"json"|"txt"){if(!scan)return;const stamp=new Date(scan.finishedAt).toISOString().replace(/[:.]/g,"-");let body:string,type:string,ext:string;if(format==="json"){body=JSON.stringify(scan,null,2);type="application/json";ext="json"}else{body=[`MPW SITE HEALTH REPORT`,`Site: ${scan.site}`,`Completed: ${new Date(scan.finishedAt).toLocaleString()}`,`PASS ${scan.totals.pass} | WARNING ${scan.totals.warning} | FAILED ${scan.totals.failed}`,"",...scan.checks.map(c=>`[${c.status.toUpperCase()}] ${c.group} — ${c.name}\n${c.detail}${c.status!=="pass"?`\nHow to fix: ${c.fix}`:""}${c.url?`\nURL: ${c.url}`:""}\n`)].join("\n");type="text/plain";ext="txt"}const blob=new Blob([body],{type});const url=URL.createObjectURL(blob);const a=document.createElement("a");a.href=url;a.download=`mpw-site-health-${stamp}.${ext}`;a.click();URL.revokeObjectURL(url)}
 const visible=(scan?.checks||[]).filter(c=>filter==="all"||c.status===filter);
 const groups=[...new Set(visible.map(c=>c.group))];
 return <>
  <div className="healthHero panel"><div><span className="eyebrow">Admin diagnostics</span><h2>MPW Site Health</h2><p className="meta">Runs read-only production checks. It does not charge cards, send emails, alter vendor/couple data, or change production code.</p></div><button className="btn primary healthRun" onClick={run} disabled={running}>{running?"Scanning MPW…":"Run Full Site Scan"}</button></div>
  {error&&<div className="notice error">{error}</div>}{fixMessage&&<div className="notice success">{fixMessage}</div>}{fixMessage&&<div className="notice success">{fixMessage}</div>}
  {scan&&<><div className="grid stats healthStats"><div className="stat healthPass"><span>PASS</span><strong>{scan.totals.pass}</strong></div><div className="stat healthWarn"><span>WARNING</span><strong>{scan.totals.warning}</strong></div><div className="stat healthFail"><span>FAILED</span><strong>{scan.totals.failed}</strong></div><div className="stat"><span>Pages scanned</span><strong>{scan.summary.pagesScanned}</strong></div><div className="stat"><span>Links checked</span><strong>{scan.summary.internalLinksChecked}</strong></div><div className="stat"><span>Scan time</span><strong>{(scan.durationMs/1000).toFixed(1)}s</strong></div></div>
  <div className="healthToolbar"><div><button onClick={()=>setFilter("all")} className={filter==="all"?"active":""}>All</button><button onClick={()=>setFilter("failed")} className={filter==="failed"?"active":""}>Failed</button><button onClick={()=>setFilter("warning")} className={filter==="warning"?"active":""}>Warnings</button><button onClick={()=>setFilter("pass")} className={filter==="pass"?"active":""}>Passed</button></div><div className="healthExport"><button className="btn primary" onClick={autoFix} disabled={fixing||running}>{fixing?"Applying Safe Fixes…":"Auto Fix Safe Issues"}</button><button onClick={()=>download("txt")}>Download Report</button><button onClick={()=>download("json")}>Download JSON</button></div><small>Completed {new Date(scan.finishedAt).toLocaleString()}</small></div>
  {groups.map(g=><section className="healthGroup" key={g}><h3>{g}</h3>{visible.filter(c=>c.group===g).map(c=><article className={`healthCheck health-${c.status}`} key={c.id}><div className="healthStatus">{c.status==="pass"?"✓":c.status==="warning"?"!":"×"}</div><div className="healthCheckBody"><div className="healthCheckTitle"><strong>{c.name}</strong><span>{c.status.toUpperCase()}</span>{c.autoFix&&c.status!=="pass"&&<em>Auto-fix candidate</em>}</div><p>{c.detail}</p>{c.status!=="pass"&&<div className="healthFix"><b>How to fix</b><span>{c.fix}</span></div>}{c.url&&<small>{c.url}</small>}</div></article>)}</section>)}</>}
  <details className="panel dashboardPanel adminWindow healthHistory"><summary><span><b>Scan history</b><small>{history.length} scan{history.length===1?"":"s"} stored in this browser</small></span><i>Open</i></summary><div className="adminWindowBody">{history.length?<div className="healthHistoryList">{history.map((h,i)=><button key={h.finishedAt+i} onClick={()=>setScan(h)}><span>{new Date(h.finishedAt).toLocaleString()}</span><b>✓ {h.totals.pass} &nbsp; ! {h.totals.warning} &nbsp; × {h.totals.failed}</b></button>)}</div>:<p className="meta">Run your first scan to begin history.</p>}</div></details>
 </>;
}
