import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { createSupabaseServerClient } from "../../../../lib/supabase/server";
import { categories, oregonServiceCities, plans } from "../../../../lib/site";
import { decodeDisplayText } from "../../../../lib/text";
import BadgePresenceChecker from "../../../../components/BadgePresenceChecker";

const stages=["lead","sold","setup_sent","payment_pending","active","paused","lost"];
export default async function VendorManage({params,searchParams}:{params:Promise<{id:string}>,searchParams:Promise<{message?:string,error?:string}>}){
 const {id}=await params; const q=await searchParams; const supabase=await createSupabaseServerClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) redirect("/admin/login"); const {data:admin}=await supabase.from("admin_users").select("user_id").eq("user_id",user.id).maybeSingle(); if(!admin) redirect("/admin/login?error=Admin%20access%20required");
 const [{data:v},{data:subs},{data:leads},{data:reviews},{data:photos}]=await Promise.all([
  supabase.from("vendor_profiles").select("*").eq("id",id).maybeSingle(),
  supabase.from("subscriptions").select("*").eq("vendor_id",id).order("created_at",{ascending:false}).limit(5),
  supabase.from("leads").select("id,name,email,status,created_at").eq("vendor_id",id).order("created_at",{ascending:false}).limit(10),
  supabase.from("reviews").select("id,rating,title,body,status,created_at").eq("vendor_id",id).order("created_at",{ascending:false}).limit(25),
  supabase.from("vendor_photos").select("id").eq("vendor_id",id)
 ]); if(!v) notFound();
 const pendingReviews=(reviews||[]).filter((r:any)=>r.status==="pending");
 return <main><section className="pagehero"><div className="container"><span className="eyebrow">Vendor CRM</span><h1>{decodeDisplayText(v.business_name)}</h1><p>{v.email||"No email"}{v.phone?` · ${v.phone}`:""}</p></div></section><section className="section"><div className="container"><div className="adminCrmTopbar"><Link className="btn light" href="/admin/vendors">← All Vendors</Link>{v.status==="active"&&<Link className="btn light" href={`/vendors/${v.slug}`}>View Public Listing</Link>}<Link className="btn primary" href={`/vendor/dashboard?admin_preview=${v.id}`}>Preview Vendor Dashboard</Link></div>{q.message&&<div className="notice success">{q.message}</div>}{q.error&&<div className="notice error">{q.error}</div>}
 <div className="grid stats"><div className="stat"><span className="meta">Plan</span><strong>{plans[v.plan as keyof typeof plans]?.name||v.plan}</strong></div><div className="stat"><span className="meta">Listing</span><strong>{v.status}</strong></div><div className="stat"><span className="meta">Leads</span><strong>{leads?.length||0}</strong></div><div className="stat"><span className="meta">Photos</span><strong>{photos?.length||0}</strong></div><div className="stat"><span className="meta">Reviews to approve</span><strong>{pendingReviews.length}</strong></div></div>
 <div className="crmTwoCol"><div className="panel dashboardPanel"><span className="eyebrow">Account</span><h2>Edit vendor</h2><form action="/api/admin/vendor-update" method="post" className="formGrid"><input type="hidden" name="vendor_id" value={v.id}/><div className="field"><label>Business name</label><input name="business_name" defaultValue={v.business_name||""} required/></div><div className="field"><label>Email</label><input type="email" name="email" defaultValue={v.email||""}/></div><div className="field"><label>Phone</label><input name="phone" defaultValue={v.phone||""}/></div><div className="field"><label>Website</label><input name="website" defaultValue={v.website||""}/></div><div className="field"><label>Plan</label><select name="plan" defaultValue={v.plan}>{Object.entries(plans).map(([k,p])=><option key={k} value={k}>{p.name}</option>)}</select></div><div className="field"><label>Listing status</label><select name="status" defaultValue={v.status}><option value="draft">Draft</option><option value="pending">Pending</option><option value="active">Active</option><option value="suspended">Suspended</option></select></div><div className="field"><label>CRM stage</label><select name="crm_stage" defaultValue={v.crm_stage||"lead"}>{stages.map(s=><option key={s} value={s}>{s.replaceAll("_"," ")}</option>)}</select></div><div className="field"><label>Primary category</label><select name="primary_category" defaultValue={v.primary_category}>{categories.map(([slug,name])=><option key={slug} value={slug}>{name}</option>)}</select></div><div className="field"><label>Last contacted</label><input type="date" name="last_contact_at" defaultValue={v.last_contact_at?String(v.last_contact_at).slice(0,10):""}/></div><div className="field"><label>Next follow-up</label><input type="date" name="next_follow_up_at" defaultValue={v.next_follow_up_at?String(v.next_follow_up_at).slice(0,10):""}/></div><div className="field full"><label>Service cities</label><div className="serviceCityGrid compactCities">{oregonServiceCities.map(city=><label className="cityCheck" key={city}><input type="checkbox" name="service_cities" value={city} defaultChecked={(v.service_cities||[]).includes(city)}/><span>{city}</span></label>)}</div></div><div className="field full"><label>Internal admin notes</label><textarea name="admin_notes" rows={7} defaultValue={v.admin_notes||""} placeholder="Sales notes, account history, preferences, follow-up details…"/></div><div className="field full"><button className="btn primary">Save Vendor Changes</button></div></form></div>
 <div><div className="panel dashboardPanel"><span className="eyebrow">Billing</span><h2>Membership status</h2>{subs?.length?subs.map((s:any)=><div className="crmMiniRow" key={s.id}><strong>{s.plan}</strong><span>{s.status}</span><span className="meta">{s.current_period_end?`Through ${new Date(s.current_period_end).toLocaleDateString()}`:""}</span></div>):<p className="meta">No subscription record yet.</p>}<p className="meta">Payment management will connect to Global Payments/Genius once that API is activated.</p></div><div className="panel dashboardPanel"><span className="eyebrow">Activity</span><h2>Recent leads</h2>{leads?.length?leads.map((l:any)=><div className="crmMiniRow" key={l.id}><strong>{decodeDisplayText(l.name||"Inquiry")}</strong><span>{l.status}</span><span className="meta">{new Date(l.created_at).toLocaleDateString()}</span></div>):<p className="meta">No leads yet.</p>}<h3 className="crmSubheading">Recent reviews</h3>{reviews?.length?reviews.map((r:any)=><div className="crmMiniRow" key={r.id}><strong>{"★".repeat(Number(r.rating))} {decodeDisplayText(r.title||"")}</strong><span>{r.status}</span></div>):<p className="meta">No reviews yet.</p>}</div></div></div>
 <BadgePresenceChecker vendorId={v.id}/>
 <div id="reviews" className={`panel dashboardPanel vendorReviewApproval ${pendingReviews.length?"needsAttention":""}`}><div className="crmSectionHeader"><div><span className="eyebrow">Reviews</span><h2>{pendingReviews.length?`${pendingReviews.length} review${pendingReviews.length===1?"":"s"} waiting for approval`:"Review moderation"}</h2><p className="meta">Review decisions for this business stay attached to this vendor record.</p></div></div>{pendingReviews.length?<div className="reviewModeration">{pendingReviews.map((r:any)=><article className="adminReview" key={r.id}><div><span className="eyebrow">{new Date(r.created_at).toLocaleDateString()}</span><h3>{"★".repeat(Number(r.rating))} {decodeDisplayText(r.title||"")}</h3><p>{decodeDisplayText(r.body||"")}</p></div><div className="reviewActions"><form action="/api/admin/review-status" method="post"><input type="hidden" name="review_id" value={r.id}/><input type="hidden" name="status" value="approved"/><input type="hidden" name="return_to" value={`/admin/vendors/${v.id}#reviews`}/><button className="btn primary">Approve</button></form><form action="/api/admin/review-status" method="post"><input type="hidden" name="review_id" value={r.id}/><input type="hidden" name="status" value="rejected"/><input type="hidden" name="return_to" value={`/admin/vendors/${v.id}#reviews`}/><button className="btn light">Reject</button></form></div></article>)}</div>:<p className="meta">No reviews for this vendor need approval.</p>}</div> <div className="panel dashboardPanel dangerZone"><span className="eyebrow">Danger zone</span><h2>Remove vendor completely</h2><p>This permanently removes the vendor profile, listing photos, leads, reviews, favorites, analytics and associated marketplace data. If the vendor has a dedicated Supabase login, that login is also removed. This cannot be undone.</p><form action="/api/admin/vendor-delete" method="post"><input type="hidden" name="vendor_id" value={v.id}/><label className="dangerConfirm"><input type="checkbox" name="confirm" value="DELETE" required/> I understand this permanently deletes the vendor and its marketplace data.</label><button className="btn danger">Permanently Delete Vendor</button></form></div>
 </div></section></main>
}
