import { categories } from "../../lib/site";
import { createSupabaseServerClient } from "../../lib/supabase/server";
import { decodeDisplayText } from "../../lib/text";
import VendorTierBadge from "../../components/VendorTierBadge";
import Link from "next/link";
const weight:Record<string,number>={premium:4,professional:3,pro:3,basic:2,free:1};
function photoUrl(path?:string|null){return path&&process.env.NEXT_PUBLIC_SUPABASE_URL?`${process.env.NEXT_PUBLIC_SUPABASE_URL}/storage/v1/object/public/vendor-media/${path}`:null}
export const metadata={title:"Portland Wedding Vendors & Venues",description:"Browse Portland-area wedding vendors and venues by category and location. Discover local professionals and build a wedding team that fits your plans.",alternates:{canonical:"/vendors"},openGraph:{title:"Portland Wedding Vendors & Venues",description:"Browse Portland-area wedding vendors and venues by category and location. Discover local professionals and build a wedding team that fits your plans.",url:"/vendors",images:[{url:"/brand/mpw-social-share.png",width:1200,height:630,alt:"My Portland Wedding — Plan Local. Love Always."}]}};
type Q={q?:string;area?:string;category?:string};
export default async function Vendors({searchParams}:{searchParams:Promise<Q>}){
 const q=await searchParams;
 const supabase=await createSupabaseServerClient();
 const {data}=await supabase.from("vendor_profiles").select("id,slug,business_name,primary_category,secondary_categories,city,state,service_cities,description,plan,rating,founding_vendor,vendor_photos(storage_path,sort_order)").eq("market_slug","portland").eq("status","active").limit(500);
 let vendors=(data||[]) as any[];
 const ranked=[...vendors].sort((a:any,b:any)=>(Number(b.founding_vendor)-Number(a.founding_vendor))||(weight[String(b.plan||"").toLowerCase()]||0)-(weight[String(a.plan||"").toLowerCase()]||0)||(Number(b.rating||0)-Number(a.rating||0))||String(a.business_name||"").localeCompare(String(b.business_name||"")));
 if(q.q){const n=q.q.toLowerCase();vendors=vendors.filter(v=>`${v.business_name||""} ${v.description||""}`.toLowerCase().includes(n));}
 if(q.category)vendors=vendors.filter(v=>v.primary_category===q.category||(v.secondary_categories||[]).includes(q.category));
 if(q.area){const area=q.area.toLowerCase();vendors=vendors.filter(v=>String(v.city||"").toLowerCase()===area||(v.service_cities||[]).some((city:string)=>String(city).toLowerCase()===area));}
 vendors=vendors.sort((a:any,b:any)=>(Number(b.founding_vendor)-Number(a.founding_vendor))||(weight[String(b.plan||"").toLowerCase()]||0)-(weight[String(a.plan||"").toLowerCase()]||0)||(Number(b.rating||0)-Number(a.rating||0))||String(a.business_name||"").localeCompare(String(b.business_name||"")));
 const searching=Boolean(q.q||q.category||q.area);
 return <main>
  <section className="pagehero vendorBrowseHero"><div className="container"><span className="eyebrow">Portland + nearby Oregon</span><h1>Explore local wedding pros.</h1><p className="meta">Start with a category, peek at who is inside, then meet the vendors that feel right for your wedding.</p></div></section>
  <section className="section vendorBrowseSection"><div className="container">
   {!searching&&<><div className="vendorBrowseIntro"><div><span className="eyebrow">Explore by category</span><h2>A whole local wedding team, one category at a time.</h2></div><p>Each category gives you a quick look at real MPW vendors before you open it.</p></div><div className="vendorCategoryPreviewGrid">{categories.map(([slug,name])=>{const matches=ranked.filter(v=>v.primary_category===slug||(v.secondary_categories||[]).includes(slug));const previews=matches.slice(0,3);return <Link className="vendorCategoryPreviewCard" href={`/vendors/${slug}`} key={slug}><div className="vendorCategoryPreviewHead"><div><span>{String(matches.length).padStart(2,"0")} LOCAL</span><h3>{name}</h3></div><b>Explore →</b></div><div className="vendorCategoryFaces">{previews.length?previews.map((v:any)=>{const photos=(v.vendor_photos||[]).sort((a:any,b:any)=>(a.sort_order||0)-(b.sort_order||0));const src=photoUrl(photos[0]?.storage_path);return <div className="vendorCategoryMini" key={v.id}>{src?<img src={src} alt=""/>:<div className="vendorCategoryMiniFallback"><img src="/brand/mpw-heart-sprig-clean.png" alt=""/></div>}<span>{decodeDisplayText(v.business_name)}</span></div>}):<div className="vendorCategoryComing"><img src="/brand/mpw-heart-sprig-clean.png" alt=""/><span>More local vendors coming soon</span></div>}</div></Link>})}</div></>}
   {searching&&<><div className="vendorResultsHead"><p><strong>{vendors.length}</strong> vendors found</p><Link href="/vendors">Back to categories</Link></div><div className="vendorMarketplaceGrid">{vendors.map(v=>{const photos=(v.vendor_photos||[]).sort((a:any,b:any)=>(a.sort_order||0)-(b.sort_order||0));const src=photoUrl(photos[0]?.storage_path);const label=categories.find(([s])=>s===v.primary_category)?.[1]||v.primary_category;return <Link className="marketVendorCard" href={`/vendor/${v.slug}`} key={v.slug}><div className={`marketVendorPhoto ${src?"hasVendorPhoto":"vendorImageFallback"}`}>{src?<><img className="marketVendorBackdrop" src={src} alt="" aria-hidden="true"/><img className="marketVendorForeground" src={src} alt={`${decodeDisplayText(v.business_name)} wedding work`}/></>:<div className="mpwVendorImageFallback compact"><img src="/brand/mpw-heart-sprig-clean.png" alt=""/><span>{decodeDisplayText(label||"Wedding Pro")}</span></div>}<div className="marketVendorBadge"><VendorTierBadge plan={v.plan} foundingVendor={v.founding_vendor}/></div></div><div className="marketVendorBody"><h3>{decodeDisplayText(v.business_name)}</h3><p className="marketVendorMeta">{decodeDisplayText(v.city||"Portland")}, {v.state||"OR"} · {decodeDisplayText(label||"Wedding Pro")}{v.rating?` · ★ ${v.rating}`:""}</p><p className="marketVendorBio">{decodeDisplayText(v.description||"View profile, services and contact information.")}</p><span className="vendorCardCta">View Profile →</span></div></Link>})}</div></>}
  </div></section>
 </main>
}