"use client";
import {useMemo,useState} from "react";

const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n);

export default function EditorialMiniTool({kind}:{kind:string}){
 const [budget,setBudget]=useState(35000),[guests,setGuests]=useState(100),[date,setDate]=useState(""),[hours,setHours]=useState(8),[locations,setLocations]=useState(2),[tables,setTables]=useState(12);
 const days=useMemo(()=>date?Math.ceil((new Date(date+"T12:00:00").getTime()-Date.now())/86400000):null,[date]);
 if(kind==="budget") return <section className="editorialMiniTool"><span className="eyebrow">Make it yours</span><h2>What does your budget look like per guest?</h2><div className="miniToolInputs"><label>Total wedding budget<input type="number" min="1000" step="500" value={budget} onChange={e=>setBudget(Math.max(0,Number(e.target.value)||0))}/></label><label>Guest count<input type="number" min="1" max="1000" value={guests} onChange={e=>setGuests(Math.max(1,Number(e.target.value)||1))}/></label></div><div className="miniToolResult"><b>{money(budget/guests)}</b><span>total budget per guest</span></div><p>This is not a catering quote—it is a quick perspective check. Changing the guest count can affect several categories at once.</p></section>;
 if(kind==="cake") return <section className="editorialMiniTool"><span className="eyebrow">Dessert math, simplified</span><h2>How many servings should you plan?</h2><label>Guests<input type="number" min="1" max="1000" value={guests} onChange={e=>setGuests(Math.max(1,Number(e.target.value)||1))}/></label><div className="miniToolResult"><b>{Math.ceil(guests*1.05)}</b><span>servings with a small cushion</span></div><p>Use this as a conversation starter with your baker; serving style, other desserts and vendor guidance can change the final number.</p></section>;
 if(kind==="stationery") return <section className="editorialMiniTool"><span className="eyebrow">Put it on the calendar</span><h2>How far away is your wedding?</h2><label>Wedding date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>{days!==null&&<div className="miniToolResult"><b>{days>0?days:0}</b><span>days until the wedding</span></div>}<p>Use the timeline in this guide to work backward from your date for invitations, RSVPs and final counts.</p></section>;
 if(kind==="photography") return <section className="editorialMiniTool"><span className="eyebrow">Build the photo day</span><h2>How much photography coverage fits your timeline?</h2><div className="miniToolInputs"><label>Coverage hours<input type="number" min="2" max="16" value={hours} onChange={e=>setHours(Math.max(2,Number(e.target.value)||2))}/></label><label>Photo locations<input type="number" min="1" max="8" value={locations} onChange={e=>setLocations(Math.max(1,Number(e.target.value)||1))}/></label></div><div className="miniToolResult"><b>{Math.max(0,Math.round((hours*60-(locations-1)*30)/60*10)/10)} hrs</b><span>rough usable coverage after allowing 30 minutes between locations</span></div><p>A planning aid, not a photographer quote. Travel, first looks, family-photo lists and reception priorities can materially change the timeline.</p></section>;
 if(kind==="catering") return <section className="editorialMiniTool"><span className="eyebrow">Reception reality check</span><h2>How many guest meals are you planning around?</h2><label>Expected guests<input type="number" min="1" max="1000" value={guests} onChange={e=>setGuests(Math.max(1,Number(e.target.value)||1))}/></label><div className="miniToolResult"><b>{guests}</b><span>guest meals before vendor meals, children or special accommodations</span></div><p>Use the guide to turn this starting count into the questions your caterer needs answered about service style, staffing, rentals and dietary needs.</p></section>;
 if(kind==="rentals") return <section className="editorialMiniTool"><span className="eyebrow">Room-plan starter</span><h2>How many reception tables might you need?</h2><div className="miniToolInputs"><label>Guests<input type="number" min="1" max="1000" value={guests} onChange={e=>setGuests(Math.max(1,Number(e.target.value)||1))}/></label><label>Seats per table<input type="number" min="2" max="16" value={tables} onChange={e=>setTables(Math.max(2,Number(e.target.value)||2))}/></label></div><div className="miniToolResult"><b>{Math.ceil(guests/tables)}</b><span>guest tables as a starting estimate</span></div><p>Venue dimensions, table shape, sweetheart/head tables and accessibility needs will change the final floor plan.</p></section>;
 if(kind==="transportation") return <section className="editorialMiniTool"><span className="eyebrow">Guest movement check</span><h2>How many people may need a ride?</h2><div className="miniToolInputs"><label>Guests<input type="number" min="1" max="1000" value={guests} onChange={e=>setGuests(Math.max(1,Number(e.target.value)||1))}/></label><label>Estimated riders (%)<input type="number" min="0" max="100" value={hours*10} onChange={e=>setHours(Math.max(0,Math.min(10,(Number(e.target.value)||0)/10)))}/></label></div><div className="miniToolResult"><b>{Math.ceil(guests*hours/10)}</b><span>estimated riders to plan transportation around</span></div><p>This does not size a vehicle fleet; it gives you a headcount to discuss with transportation providers alongside hotel locations, parking and trip timing.</p></section>;
 return null;
}