"use client";
import {useMemo,useState} from "react";

const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n);

export default function EditorialMiniTool({kind}:{kind:string}){
 const [budget,setBudget]=useState(35000),[guests,setGuests]=useState(100),[date,setDate]=useState(""),[hours,setHours]=useState(8),[locations,setLocations]=useState(2),[tables,setTables]=useState(12),[partyHours,setPartyHours]=useState(5),[stems,setStems]=useState(12);
 const days=useMemo(()=>date?Math.ceil((new Date(date+"T12:00:00").getTime()-Date.now())/86400000):null,[date]);
 if(kind==="budget") return <section className="editorialMiniTool"><span className="eyebrow">Make it yours</span><h2>What does your budget look like per guest?</h2><div className="miniToolInputs"><label>Total wedding budget<input type="number" min="1000" step="500" value={budget} onChange={e=>setBudget(Math.max(0,Number(e.target.value)||0))}/></label><label>Guest count<input type="number" min="1" max="1000" value={guests} onChange={e=>setGuests(Math.max(1,Number(e.target.value)||1))}/></label></div><div className="miniToolResult"><b>{money(budget/guests)}</b><span>total budget per guest</span></div><p>This is not a catering quote—it is a quick perspective check. Changing the guest count can affect several categories at once.</p></section>;
 if(kind==="cake") return <section className="editorialMiniTool"><span className="eyebrow">Dessert math, simplified</span><h2>How many servings should you plan?</h2><label>Guests<input type="number" min="1" max="1000" value={guests} onChange={e=>setGuests(Math.max(1,Number(e.target.value)||1))}/></label><div className="miniToolResult"><b>{Math.ceil(guests*1.05)}</b><span>servings with a small cushion</span></div><p>Use this as a conversation starter with your baker; serving style, other desserts and vendor guidance can change the final number.</p></section>;

 if(kind==="photography") return <section className="editorialMiniTool"><span className="eyebrow">Build the photo day</span><h2>How much photography coverage fits your timeline?</h2><div className="miniToolInputs"><label>Coverage hours<input type="number" min="2" max="16" value={hours} onChange={e=>setHours(Math.max(2,Number(e.target.value)||2))}/></label><label>Photo locations<input type="number" min="1" max="8" value={locations} onChange={e=>setLocations(Math.max(1,Number(e.target.value)||1))}/></label></div><div className="miniToolResult"><b>{Math.max(0,Math.round((hours*60-(locations-1)*30)/60*10)/10)} hrs</b><span>rough usable coverage after allowing 30 minutes between locations</span></div><p>A planning aid, not a photographer quote. Travel, first looks, family-photo lists and reception priorities can materially change the timeline.</p></section>;
 if(kind==="catering") return <section className="editorialMiniTool"><span className="eyebrow">Reception reality check</span><h2>How many guest meals are you planning around?</h2><label>Expected guests<input type="number" min="1" max="1000" value={guests} onChange={e=>setGuests(Math.max(1,Number(e.target.value)||1))}/></label><div className="miniToolResult"><b>{guests}</b><span>guest meals before vendor meals, children or special accommodations</span></div><p>Use the guide to turn this starting count into the questions your caterer needs answered about service style, staffing, rentals and dietary needs.</p></section>;
 if(kind==="rentals") return <section className="editorialMiniTool"><span className="eyebrow">Room-plan starter</span><h2>How many reception tables might you need?</h2><div className="miniToolInputs"><label>Guests<input type="number" min="1" max="1000" value={guests} onChange={e=>setGuests(Math.max(1,Number(e.target.value)||1))}/></label><label>Seats per table<input type="number" min="2" max="16" value={tables} onChange={e=>setTables(Math.max(2,Number(e.target.value)||2))}/></label></div><div className="miniToolResult"><b>{Math.ceil(guests/tables)}</b><span>guest tables as a starting estimate</span></div><p>Venue dimensions, table shape, sweetheart/head tables and accessibility needs will change the final floor plan.</p></section>;
 if(kind==="transportation") return <section className="editorialMiniTool"><span className="eyebrow">Guest movement check</span><h2>How many people may need a ride?</h2><div className="miniToolInputs"><label>Guests<input type="number" min="1" max="1000" value={guests} onChange={e=>setGuests(Math.max(1,Number(e.target.value)||1))}/></label><label>Estimated riders (%)<input type="number" min="0" max="100" value={hours*10} onChange={e=>setHours(Math.max(0,Math.min(10,(Number(e.target.value)||0)/10)))}/></label></div><div className="miniToolResult"><b>{Math.ceil(guests*hours/10)}</b><span>estimated riders to plan transportation around</span></div><p>This does not size a vehicle fleet; it gives you a headcount to discuss with transportation providers alongside hotel locations, parking and trip timing.</p></section>;
 if(kind==="florists") return <section className="editorialMiniTool"><span className="eyebrow">Flower-count perspective</span><h2>How many table arrangements are in your plan?</h2><div className="miniToolInputs"><label>Guests<input type="number" min="1" max="1000" value={guests} onChange={e=>setGuests(Math.max(1,Number(e.target.value)||1))}/></label><label>Guests per table<input type="number" min="2" max="16" value={tables} onChange={e=>setTables(Math.max(2,Number(e.target.value)||2))}/></label></div><div className="miniToolResult"><b>{Math.ceil(guests/tables)}</b><span>guest tables that may need floral or another centerpiece treatment</span></div><p>This is a design-planning count, not a stem estimate. Your florist can help decide where flowers create the most impact and where candles, greenery or other elements make more sense.</p></section>;
 if(kind==="dj") return <section className="editorialMiniTool"><span className="eyebrow">Reception timeline check</span><h2>How much of the reception is actually open dancing?</h2><label>Reception length (hours)<input type="number" min="2" max="10" step=".5" value={partyHours} onChange={e=>setPartyHours(Math.max(2,Number(e.target.value)||2))}/></label><div className="miniToolResult"><b>{Math.max(1,Math.round((partyHours-2)*10)/10)} hrs</b><span>rough dance-floor window after allowing about two hours for entrances, dinner, toasts and formal moments</span></div><p>Every timeline is different. Use this as a prompt to discuss pacing, announcements and music priorities with your DJ or entertainment team.</p></section>;
 if(kind==="beauty") return <section className="editorialMiniTool"><span className="eyebrow">Getting-ready reality check</span><h2>How many beauty services are you coordinating?</h2><div className="miniToolInputs"><label>People receiving services<input type="number" min="1" max="30" value={guests} onChange={e=>setGuests(Math.max(1,Number(e.target.value)||1))}/></label><label>Services each<input type="number" min="1" max="2" value={locations} onChange={e=>setLocations(Math.max(1,Math.min(2,Number(e.target.value)||1)))}/></label></div><div className="miniToolResult"><b>{guests*locations}</b><span>hair/makeup service appointments to coordinate</span></div><p>Your artist should set the actual schedule. This count helps you recognize when adding artists, an earlier start or fewer services may be worth discussing.</p></section>;
 if(kind==="planning") return <section className="editorialMiniTool"><span className="eyebrow">Planning runway</span><h2>How much time do you have to plan?</h2><label>Wedding date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label>{days!==null&&<div className="miniToolResult"><b>{Math.max(0,Math.ceil(days/30.44))}</b><span>approximate months remaining</span></div>}<p>The number is less important than the sequence. Use this guide to identify the decisions that unlock the next ones instead of trying to do everything at once.</p></section>;
 if(kind==="officiant") return <section className="editorialMiniTool"><span className="eyebrow">Ceremony conversation starter</span><h2>How much ceremony time are you picturing?</h2><label>Target ceremony length (minutes)<input type="number" min="5" max="90" step="5" value={Math.round(partyHours*5)} onChange={e=>setPartyHours(Math.max(1,Number(e.target.value)||5)/5)}/></label><div className="miniToolResult"><b>{Math.round(partyHours*5)} min</b><span>your target—not a required ceremony length</span></div><p>Use that number to start a conversation about readings, vows, traditions and transitions with your officiant. Your officiant can help shape the actual ceremony.</p></section>;
 if(kind==="stationery") return <section className="editorialMiniTool"><span className="eyebrow">Invitation conversation starter</span><h2>How many households are on your guest list?</h2><div className="miniToolInputs"><label>Total guests<input type="number" min="1" max="1000" value={guests} onChange={e=>setGuests(Math.max(1,Number(e.target.value)||1))}/></label><label>Average guests per invitation<input type="number" min="1" max="8" step=".5" value={locations} onChange={e=>setLocations(Math.max(1,Number(e.target.value)||1))}/></label></div><div className="miniToolResult"><b>{Math.ceil(guests/locations)}</b><span>estimated invitations before extras</span></div><p>This is intentionally a quick print-quantity check—not a full guest-list or RSVP tool. Use MPW Planning Tools for the planning workflow itself.</p></section>;
 if(kind==="vendors") return <section className="editorialMiniTool"><span className="eyebrow">Shortlist gut-check</span><h2>What matters most before you inquire?</h2><div className="miniToolResult"><b>3 things</b><span>availability · fit · communication</span></div><p>Use the article to decide what “fit” means for this category, then let Wedding Builder and the MPW vendor directory handle the actual discovery and comparison.</p></section>;
 if(kind==="local") return <section className="editorialMiniTool"><span className="eyebrow">Make it feel like Portland</span><h2>Pick one local layer—not ten.</h2><div className="miniToolResult"><b>1</b><span>meaningful local touch can feel more intentional than a pile of themes</span></div><p>Think neighborhood, food, landscape, season or a place you actually love. The article gives you prompts without turning your wedding into a Portland checklist.</p></section>;
 if(kind==="season") return <section className="editorialMiniTool"><span className="eyebrow">Season personality</span><h2>What should your date work hardest for?</h2><div className="seasonPromptGrid"><span>Longer light</span><span>Cozy atmosphere</span><span>Outdoor comfort</span><span>Seasonal color</span></div><p>There is no universally “best” Portland wedding month. Use the weather-and-season guide to compare the tradeoffs, then the venue date tools for daylight and historical weather context.</p></section>;
 if(kind==="micro") return <section className="editorialMiniTool"><span className="eyebrow">Small wedding, big priorities</span><h2>What changes when the guest list gets smaller?</h2><div className="miniToolInputs"><label>Guest count<input type="number" min="2" max="75" value={guests} onChange={e=>setGuests(Math.max(2,Number(e.target.value)||2))}/></label><label>Total budget<input type="number" min="1000" step="500" value={budget} onChange={e=>setBudget(Math.max(0,Number(e.target.value)||0))}/></label></div><div className="miniToolResult"><b>{money(budget/guests)}</b><span>budget per guest—not a spending target</span></div><p>A smaller guest list can change where your money has impact. Use this as perspective only; MPW Planning Tools remain the place to manage the actual wedding budget.</p></section>;
 if(kind==="diy") return <section className="editorialMiniTool"><span className="eyebrow">DIY reality check</span><h2>Before you DIY it, count the hidden jobs.</h2><div className="seasonPromptGrid"><span>Source</span><span>Build</span><span>Transport</span><span>Set up</span></div><p>If a project needs all four, compare the time and logistics—not only the material price—before deciding it is the budget-friendly choice.</p></section>;
 return null;
}