import Link from "next/link";
import Image from "next/image";
import { notFound } from "next/navigation";
import { inspirationArticles } from "../../../lib/content";
import { createAdminClient } from "../../../lib/supabase/admin";
import { decodeDisplayText } from "../../../lib/text";
import type { Metadata } from "next";
import { categories } from "../../../lib/site";

export function generateStaticParams(){return inspirationArticles.map(a=>({slug:a.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const a=inspirationArticles.find(x=>x.slug===slug);if(!a)return {};const path=`/inspiration/${a.slug}`;const image=a.heroImage?.src||"/brand/mpw-social-share.png";return {title:a.seoTitle||a.title,description:a.seoDescription||a.dek,alternates:{canonical:path},openGraph:{title:a.seoTitle||a.title,description:a.seoDescription||a.dek,url:path,type:"article",publishedTime:a.publishedAt,modifiedTime:a.updatedAt,images:[{url:image,alt:a.heroImage?.alt||`${a.title} — My Portland Wedding`}]},twitter:{card:"summary_large_image",title:a.seoTitle||a.title,description:a.seoDescription||a.dek,images:[image]}}}

function vendorImage(v:any,feature:any){
 if(feature?.image_url)return feature.image_url;
 if(v?.profile_image_url)return v.profile_image_url;
 return "/brand/mpw-master-logo-no-flare.png";
}

export default async function Page({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const a=inspirationArticles.find(x=>x.slug===slug);if(!a)notFound();
 const admin=createAdminClient();
 const {data:features}=await admin.from("inspiration_article_features").select("id,vendor_id,eyebrow,headline,blurb,image_url,sort_order").eq("article_slug",a.slug).eq("active",true).order("sort_order").limit(3);
 const vendorIds=(features||[]).map((x:any)=>x.vendor_id);
 const {data:vendors}=vendorIds.length?await admin.from("vendor_profiles").select("id,business_name,slug,description,city,state,profile_image_url,primary_category,plan,founding_vendor").in("id",vendorIds).eq("status","active"):{data:[] as any[]};
 const featured=(features||[]).map((feature:any)=>({feature,vendor:(vendors||[]).find((v:any)=>v.id===feature.vendor_id)})).filter((x:any)=>x.vendor);
 const articleSchema={"@context":"https://schema.org","@type":"Article",headline:a.title,description:a.seoDescription||a.dek,image:a.heroImage?[a.heroImage.src]:undefined,datePublished:a.publishedAt,dateModified:a.updatedAt,author:{"@type":"Organization",name:"My Portland Wedding",url:"https://www.myportlandwedding.com/about"},publisher:{"@type":"Organization",name:"My Portland Wedding",url:"https://www.myportlandwedding.com",logo:{"@type":"ImageObject",url:"https://www.myportlandwedding.com/brand/mpw-master-logo-no-flare.png"}},mainEntityOfPage:{"@type":"WebPage","@id":`https://www.myportlandwedding.com/inspiration/${a.slug}`},about:{"@type":"Thing","name":a.category+" weddings in Portland, Oregon"}};
 const faqSchema=a.faq?{"@context":"https://schema.org","@type":"FAQPage",mainEntity:a.faq.map(f=>({"@type":"Question",name:f.question,acceptedAnswer:{"@type":"Answer",text:f.answer}}))}:null;
 return <main className="magazineArticle"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(articleSchema)}} /><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumbSchema)}} />{faqSchema&&<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}} />}
 <section className="articleHero magazineHero">${a.heroImage?<div className="magazineHeroPhoto"><Image src={a.heroImage.src} alt={a.heroImage.alt} fill priority sizes="100vw"/><div className="magazinePhotoShade"/>{(a.heroImage.caption||a.heroImage.credit)&&<p className="photoCredit">{a.heroImage.caption}{a.heroImage.caption&&a.heroImage.credit?" · ":""}{a.heroImage.credit}</p>}</div>:null}<div className="narrow"><span className="eyebrow">{a.category} · The Portland Wedding Edit</span><h1>{a.title}</h1><p className="articleDek">{a.dek}</p><div className="articleMeta topMeta"><span>{a.readTime}</span><span>My Portland Wedding Editorial</span></div></div></section>
 <article className="articleBody magazineBody narrow">
  <nav className="articleBreadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><span>›</span><Link href="/inspiration">Inspiration</Link><span>›</span><span>{a.category}</span></nav><div className="articleLead"><span className="dropCap">P</span><p>Planning in Portland is wonderfully specific: weather, neighborhoods, guest logistics and a deep bench of local wedding professionals all shape the day. This guide is designed to be saved, shared and actually used—not skimmed and forgotten.</p></div>
  <div className="inspirationBuilderCard"><span>♡</span><div><strong>Build this around your wedding.</strong><p>Give Wedding Builder your budget, vibe and priorities for a personalized local vendor roster and category-by-category plan.</p></div><Link className="btn light" href={`/wedding-builder?style=${encodeURIComponent(a.category==="Local Ideas"?"Romantic & Garden":a.category==="Venues"?"Classic & Elegant":"Romantic & Garden")}`}>Try Wedding Builder — Free ✨</Link></div>
  {a.sections.map((s,index)=><section className="magazineSection" key={s.heading}><div className="sectionNumber">{String(index+1).padStart(2,"0")}</div><div><h2>{s.heading}</h2>{s.image&&<figure className="editorialFigure"><div className="editorialFigureImage"><Image src={s.image.src} alt={s.image.alt} fill sizes="(max-width: 760px) 100vw, 820px"/></div>{(s.image.caption||s.image.credit)&&<figcaption>{s.image.caption}{s.image.caption&&s.image.credit?" · ":""}{s.image.credit}</figcaption>}</figure>}{s.paragraphs?.map((p,i)=><p className={i===0?"sectionLead":""} key={p}>{p}</p>)}{s.pullQuote&&<blockquote className="editorialPullQuote">“{s.pullQuote}”</blockquote>}{s.bullets&&<ul className="editorialList">{s.bullets.map(b=><li key={b}>{b}</li>)}</ul>}</div></section>)}
  {featured.length>0&&<section className="featuredVendorEditorial"><div className="featuredVendorHeading"><span className="eyebrow">Local expertise, beautifully done</span><h2>Featured Portland wedding pros</h2><p>Meet local professionals connected to this guide. Explore their work, approach and MPW profile as you build your vendor shortlist.</p></div><div className="featuredVendorGrid">{featured.map(({feature,vendor}:any)=><Link href={`/vendor/${vendor.slug}`} className="featuredVendorStory" key={feature.id}><div className="featuredVendorImage"><Image src={vendorImage(vendor,feature)} alt={`${decodeDisplayText(vendor.business_name)} — Portland wedding vendor`} fill sizes="(max-width: 760px) 100vw, 33vw"/></div><div className="featuredVendorCopy"><span className="eyebrow">{feature.eyebrow||"Featured Portland Wedding Pro"}</span><h3>{feature.headline||decodeDisplayText(vendor.business_name)}</h3><p>{feature.blurb||decodeDisplayText(vendor.description||`${vendor.city||"Portland"} wedding professional featured by My Portland Wedding.`)}</p><strong>Explore {decodeDisplayText(vendor.business_name)} →</strong></div></Link>)}</div><p className="featuredDisclosure">Featured vendors are identified as such. MPW editorial guidance remains separate from paid placement.</p></section>}
  {a.checklist&&<aside className="articleChecklist magazineChecklist"><span className="eyebrow">The tear-out page</span><h2>Save this planning checklist</h2><ul>{a.checklist.map(i=><li key={i}>{i}</li>)}</ul></aside>}
  {a.faq&&<section className="articleFaq magazineFaq"><span className="eyebrow">Ask MPW</span><h2>Portland wedding planning FAQ</h2>{a.faq.map(f=><div key={f.question} className="faqItem"><h3>{f.question}</h3><p>{f.answer}</p></div>)}</section>}
  {categoryMatch?<aside className="articleCategoryBridge"><span className="eyebrow">Find your local team</span><div><h2>Explore {categoryMatch[1]} in the Portland area</h2><p>Ready to move from research to a shortlist? Browse local MPW professionals in this category, then use Wedding Builder to see how they fit your priorities and budget.</p></div><Link className="btn light" href={`/vendors/${categoryMatch[0]}`}>Browse {categoryMatch[1]} →</Link></aside>:null}{a.relatedSlugs?.length?<section className="relatedEditorial"><span className="eyebrow">Keep planning</span><h2>Related Portland wedding guides</h2><div className="relatedEditorialGrid">{a.relatedSlugs.map(slug=>{const related=inspirationArticles.find(x=>x.slug===slug);return related?<Link href={`/inspiration/${related.slug}`} key={slug}><span>{related.category}</span><strong>{related.title}</strong><p>{related.dek}</p></Link>:null})}</div></section>:null}
  <div className="articleFooter"><Link className="btn light" href="/inspiration">← More Inspiration</Link><Link className="btn primary" href="/wedding-builder">Use this in Wedding Builder →</Link></div>
 </article></main>
}