import Link from "next/link";
import { notFound } from "next/navigation";
import { inspirationArticles } from "../../../lib/content";
import type { Metadata } from "next";
export function generateStaticParams(){return inspirationArticles.map(a=>({slug:a.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const a=inspirationArticles.find(x=>x.slug===slug);if(!a)return {};const path=`/inspiration/${a.slug}`;return {title:a.title,description:a.dek,alternates:{canonical:path},openGraph:{title:a.title,description:a.dek,url:path,type:"article",images:[{url:"/brand/mpw-social-share.png",width:1200,height:630,alt:`${a.title} — My Portland Wedding`}]},twitter:{card:"summary_large_image",title:a.title,description:a.dek,images:["/brand/mpw-social-share.png"]}}}
export default async function Page({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const a=inspirationArticles.find(x=>x.slug===slug);if(!a)notFound();const articleSchema={"@context":"https://schema.org","@type":"Article",headline:a.title,description:a.dek,author:{"@type":"Organization",name:"My Portland Wedding"},publisher:{"@type":"Organization",name:"My Portland Wedding"},mainEntityOfPage:`https://www.myportlandwedding.com/inspiration/${a.slug}`};const faqSchema=a.faq?{"@context":"https://schema.org","@type":"FAQPage",mainEntity:a.faq.map(f=>({"@type":"Question",name:f.question,acceptedAnswer:{"@type":"Answer",text:f.answer}}))}:null;return <main><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(articleSchema)}} />{faqSchema&&<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqSchema)}} />}
<section className="articleHero"><div className="narrow"><span className="eyebrow">{a.category}</span><h1>{a.title}</h1><p className="articleDek">{a.dek}</p><div className="articleMeta topMeta"><span>{a.readTime}</span><span>My Portland Wedding</span></div></div></section>
<article className="articleBody narrow"><div className="inspirationBuilderCard"><span>♡</span><div><strong>Build this around your wedding.</strong><p>Give Wedding Builder your budget, vibe and priorities for a personalized local vendor roster and category-by-category plan.</p></div><Link className="btn light" href={`/wedding-builder?style=${encodeURIComponent(a.category==="Local Ideas"?"Romantic & Garden":a.category==="Venues"?"Classic & Elegant":"Romantic & Garden")}`}>Try Wedding Builder — Free ✨</Link></div>{a.sections.map(s=><section key={s.heading}><h2>{s.heading}</h2>{s.paragraphs?.map(p=><p key={p}>{p}</p>)}{s.bullets&&<ul>{s.bullets.map(b=><li key={b}>{b}</li>)}</ul>}</section>)}{a.checklist&&<aside className="articleChecklist"><span className="eyebrow">Quick checklist</span><h2>Take this with you</h2><ul>{a.checklist.map(i=><li key={i}>{i}</li>)}</ul></aside>}{a.faq&&<section className="articleFaq"><span className="eyebrow">Common questions</span><h2>Portland wedding planning FAQ</h2>{a.faq.map(f=><div key={f.question} className="faqItem"><h3>{f.question}</h3><p>{f.answer}</p></div>)}</section>}<div className="articleFooter"><Link className="btn light" href="/inspiration">← More Inspiration</Link><Link className="btn primary" href="/wedding-builder">Use this in Wedding Builder →</Link></div></article>
</main>}
