import Link from "next/link";
import Image from "next/image";
import { notFound } from "next/navigation";
import { inspirationArticles } from "../../../lib/content";
import { createAdminClient } from "../../../lib/supabase/admin";
import { decodeDisplayText } from "../../../lib/text";
import type { Metadata } from "next";
import { categories } from "../../../lib/site";
import VenueDateTools from "./VenueDateTools";
import EditorialMiniTool from "./EditorialMiniTool";

export function generateStaticParams(){return inspirationArticles.map(a=>({slug:a.slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const a=inspirationArticles.find(x=>x.slug===slug);if(!a)return {};const path=`/inspiration/${a.slug}`;const image=a.heroImage?.src||"/brand/mpw-social-share.png";return {title:a.seoTitle||a.title,description:a.seoDescription||a.dek,alternates:{canonical:path},openGraph:{title:a.seoTitle||a.title,description:a.seoDescription||a.dek,url:path,type:"article",publishedTime:a.publishedAt,modifiedTime:a.updatedAt,images:[{url:image,alt:a.heroImage?.alt||`${a.title} — My Portland Wedding`}]},twitter:{card:"summary_large_image",title:a.seoTitle||a.title,description:a.seoDescription||a.dek,images:[image]}}}

function vendorImage(v:any,feature:any){
 if(feature?.image_url)return feature.image_url;
 if(v?.profile_image_url)return v.profile_image_url;
 return "/brand/mpw-master-logo-no-flare.png";
}

export default async function Page({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params;const a=inspirationArticles.find(x=>x.slug===slug);if(!a)notFound();
 const admin=createAdminClient();
 const {data:features}=await admin.from("inspiration_article_features").select("id,vendor_id,eyebrow,headline,blurb,image_url,sort_order").eq("article_slug",a.slug).eq("active",true).order("sort_order").limit(3);
 const vendorIds=(features||[]).map((x:any)=>x.vendor_id);
 const {data:vendors}=vendorIds.length?await admin.from("vendor_profiles").select("id,business_name,slug,description,city,state,profile_image_url,primary_category,plan,founding_vendor").in("id",vendorIds).eq("status","active"):{data:[] as any[]};
 const featured=(features||[]).map((feature:any)=>({feature,vendor:(vendors||[]).find((v:any)=>v.id===feature.vendor_id)})).filter((x:any)=>x.vendor);
 const articleSchema={"@context":"https://schema.org","@type":"Article",headline:a.title,description:a.seoDescription||a.dek,image:a.heroImage?[a.heroImage.src]:undefined,datePublished:a.publishedAt,dateModified:a.updatedAt,author:{"@type":"Organization",name:"My Portland Wedding",url:"https://www.myportlandwedding.com/about"},publisher:{"@type":"Organization",name:"My Portland Wedding",url:"https://www.myportlandwedding.com",logo:{"@type":"ImageObject",url:"https://www.myportlandwedding.com/brand/mpw-master-logo-no-flare.png"}},mainEntityOfPage:{"@type":"WebPage","@id":`https://www.myportlandwedding.com/inspiration/${a.slug}`},about:{"@type":"Thing","name":a.category+" weddings in Portland, Oregon"}};
 const categoryMatch=categories.find(([slug,name])=>name.toLowerCase().includes(a.category.toLowerCase())||a.category.toLowerCase().includes(name.toLowerCase()));
 const breadcrumbSchema={"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":"https://www.myportlandwedding.com/"},{"@type":"ListItem","position":2,"name":"Inspiration","item":"https://www.myportlandwedding.com/inspiration"},{"@type":"ListItem","position":3,"name":a.title,"item":`https://www.myportlandwedding.com/inspiration/${a.slug}`}]};
 return <main className="magazineArticle"><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(articleSchema)}} /><script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(breadcrumbSchema)}} />
 <section className="articleHero magazineHero">{a.category==="Venues"?<div className="seasonVenueHero" aria-label="Oregon wedding venues through four seasons"><div className="seasonVenuePanel"><img src="https://static.wixstatic.com/media/2f014d_6e0a4ee112f047198d2cfade76583ccd~mv2.jpg/v1/fill/w_1000,h_667,al_c,q_85/2f014d_6e0a4ee112f047198d2cfade76583ccd~mv2.jpg" alt="Spring garden wedding venue near Portland"/><span>Spring</span></div><div className="seasonVenuePanel"><img src="https://images.squarespace-cdn.com/content/v1/569fb1fccbced6e361e09b11/1686599015269-O7DUIRJ7I3BTX7ASJKDY/BND_6136.jpg" alt="Summer outdoor wedding venue in Oregon"/><span>Summer</span></div><div className="seasonVenuePanel"><img src="https://images.squarespace-cdn.com/content/v1/5f62ab5be79e0b612593b00b/deeabd48-d4c3-42b8-8515-0565fdff8f2f/Farm-on-Golden-Hill-Wedding.jpg" alt="Fall vineyard wedding venue in Oregon"/><span>Fall</span></div><div className="seasonVenuePanel"><img src="https://timberlinelodge.com/site/assets/files/17801/winter_wedding.600x571.webp" alt="Winter wedding at Timberline Lodge on Mount Hood"/><span>Winter</span></div><p className="seasonVenueCredit">Spring: Abernethy Center · Summer: Horning's Hideout · Fall: Farm on Golden Hill · Winter: Timberline Lodge</p></div>:a.heroImage?<div className="magazineHeroPhoto"><Image src={a.heroImage.src} alt={a.heroImage.alt} fill priority sizes="100vw"/><div className="magazinePhotoShade"/>{(a.heroImage.caption||a.heroImage.credit)&&<p className="photoCredit">{a.heroImage.caption}{a.heroImage.caption&&a.heroImage.credit?" · ":""}{a.heroImage.credit}</p>}</div>:null}<div className="narrow"><span className="eyebrow">{a.category} · The Portland Wedding Edit</span><h1>{a.title}</h1><p className="articleDek">{a.dek}</p><div className="articleMeta topMeta"><span>{a.readTime}</span><span>My Portland Wedding Editorial</span>{a.updatedAt&&<span>Updated {new Date(a.updatedAt).toLocaleDateString("en-US",{month:"long",day:"numeric",year:"numeric"})}</span>}</div></div></section>
 <article className="articleBody magazineBody narrow">
  <nav className="articleBreadcrumbs" aria-label="Breadcrumb"><Link href="/">Home</Link><span>›</span><Link href="/inspiration">Inspiration</Link><span>›</span><span>{a.category}</span></nav><div className="articleLead"><span className="dropCap">P</span><p>Planning in Portland is wonderfully specific: weather, neighborhoods, guest logistics and a deep bench of local wedding professionals all shape the day. This guide is designed to be saved, shared and actually used—not skimmed and forgotten.</p></div>
  <div className="venueMoodBoard"><div><span>01</span><strong>City Energy</strong><small>Hotels · rooftops · urban rooms</small></div><div><span>02</span><strong>Garden Romance</strong><small>Greenhouses · gardens · estates</small></div><div><span>03</span><strong>PNW Escape</strong><small>Forest · river · mountain mood</small></div><div><span>04</span><strong>Dinner-Party Magic</strong><small>Restaurants · intimate spaces</small></div></div>
  {a.category==="Venues"&&<VenueDateTools/>}{a.category==="Budget"&&<EditorialMiniTool kind="budget"/>}{a.category==="Cakes"&&<EditorialMiniTool kind="cake"/>}{a.category==="Stationery"&&<EditorialMiniTool kind="stationery"/>}{a.category==="Photography"&&<EditorialMiniTool kind="photography"/>}{a.category==="Catering"&&<EditorialMiniTool kind="catering"/>}{a.category==="Rentals"&&<EditorialMiniTool kind="rentals"/>}{a.category==="Transportation"&&<EditorialMiniTool kind="transportation"/>}\n  <div className="inspirationBuilderCard"><span>♡</span><div><strong>Build this around your wedding.</strong><p>Give Wedding Builder your budget, vibe and priorities for a personalized local vendor roster and category-by-category plan.</p></div><Link className="btn light" href={`/wedding-builder?style=${encodeURIComponent(a.category==="Local Ideas"?"Romantic & Garden":a.category==="Venues"?"Classic & Elegant":"Romantic & Garden")}`}>Try Wedding Builder — Free ✨</Link></div>
  {a.sections.map((s,index)=><section className="magazineSection" key={s.heading}><div className="sectionNumber">{String(index+1).padStart(2,"0")}</div><div><h2>{s.heading}</h2>{s.image&&<figure className="editorialFigure"><div className="editorialFigureImage"><Image src={s.image.src} alt={s.image.alt} fill sizes="(max-width: 760px) 100vw, 820px"/></div>{(s.image.caption||s.image.credit)&&<figcaption>{s.image.caption}{s.image.caption&&s.image.credit?" · ":""}{s.image.credit}</figcaption>}</figure>}{s.paragraphs?.map((p,i)=><p className={i===0?"sectionLead":""} key={p}>{p}</p>)}{s.pullQuote&&<blockquote className="editorialPullQuote">“{s.pullQuote}”</blockquote>}{s.bullets&&<ul className="editorialList">{s.bullets.map(b=><li key={b}>{b}</li>)}</ul>}</div></section>)}
  {featured.length>0&&<section className="featuredVendorEditorial"><div className="featuredVendorHeading"><span className="eyebrow">Local expertise, beautifully done</span><h2>Featured Portland wedding pros</h2><p>Meet local professionals connected to this guide. Explore their work, approach and MPW profile as you build your vendor shortlist.</p></div><div className="featuredVendorGrid">{featured.map(({feature,vendor}:any)=><Link href={`/vendor/${vendor.slug}`} className="featuredVendorStory" key={feature.id}><div className="featuredVendorImage"><Image src={vendorImage(vendor,feature)} alt={`${decodeDisplayText(vendor.business_name)} — Portland wedding vendor`} fill sizes="(max-width: 760px) 100vw, 33vw"/></div><div className="featuredVendorCopy"><span className="eyebrow">{feature.eyebrow||"Featured Portland Wedding Pro"}</span><h3>{feature.headline||decodeDisplayText(vendor.business_name)}</h3><p>{feature.blurb||decodeDisplayText(vendor.description||`${vendor.city||"Portland"} wedding professional featured by My Portland Wedding.`)}</p><strong>Explore {decodeDisplayText(vendor.business_name)} →</strong></div></Link>)}</div><p className="featuredDisclosure">Featured vendors are identified as such. MPW editorial guidance remains separate from paid placement.</p></section>}
  
  {a.checklist&&<aside className="articleChecklist magazineChecklist"><span className="eyebrow">The tear-out page</span><h2>Save this planning checklist</h2><ul>{a.checklist.map(i=><li key={i}>{i}</li>)}</ul></aside>}
  {a.faq&&<section className="articleFaq magazineFaq"><span className="eyebrow">Ask MPW</span><h2>Portland wedding planning FAQ</h2>{a.faq.map(f=><div key={f.question} className="faqItem"><h3>{f.question}</h3><p>{f.answer}</p></div>)}</section>}
  {categoryMatch?<aside className="articleCategoryBridge"><div className="articleCategoryBridgeCopy"><span className="eyebrow">Find your local team</span><h2>Explore {categoryMatch[1]} in the Portland area</h2><p>Ready to move from research to a shortlist? Browse local MPW professionals in this category, then use Wedding Builder to see how they fit your priorities and budget.</p></div><Link className="btn light articleCategoryBridgeButton" href={`/vendors/${categoryMatch[0]}`}>Browse {categoryMatch[1]} →</Link></aside>:null}{a.relatedSlugs?.length?<section className="relatedEditorial"><span className="eyebrow">Keep planning</span><h2>Related Portland wedding guides</h2><div className="relatedEditorialGrid">{a.relatedSlugs.map(slug=>{const related=inspirationArticles.find(x=>x.slug===slug);return related?<Link href={`/inspiration/${related.slug}`} key={slug}><span>{related.category}</span><strong>{related.title}</strong><p>{related.dek}</p></Link>:null})}</div></section>:null}
  {(a.reviewedBy||a.methodology||a.sources?.length)?<aside className="editorialTrust"><span className="eyebrow">How this guide was built</span>{a.reviewedBy&&<p><strong>Reviewed by:</strong> {a.reviewedBy}</p>}{a.methodology&&<p>{a.methodology}</p>}{a.sources?.length?<div className="editorialSources"><strong>Sources & references</strong>{a.sources.map(source=><a href={source.href} target="_blank" rel="noopener noreferrer" key={source.href}>{source.label} ↗</a>)}</div>:null}</aside>:null}
  <div className="articleFooter"><Link className="btn light" href="/inspiration">← More Inspiration</Link><Link className="btn primary" href="/wedding-builder">Use this in Wedding Builder →</Link></div>
 </article></main>
}