import Link from "next/link";

export const metadata={title:"Terms of Use | My Portland Wedding"};
export default function TermsOfUse(){return <main><section className="pagehero"><div className="container narrow"><span className="eyebrow">Legal</span><h1>Terms of Use</h1><p className="meta">Effective September 11, 2026 · Last updated September 11, 2026</p></div></section><section className="section"><article className="container narrow legalPage">
<p>These Terms of Use govern your access to and use of the My Portland Wedding website, directory, planning tools, vendor profiles, accounts, content and related services (the “Platform”). By accessing or using the Platform, you agree to these Terms. If you do not agree, do not use the Platform.</p>
<h2>1. About My Portland Wedding</h2><p>My Portland Wedding is a local wedding-planning platform that helps couples discover wedding venues, professionals, products and services in Portland and surrounding Oregon communities. Vendors are independent businesses and are not employees, agents, partners or representatives of My Portland Wedding unless expressly stated otherwise.</p>
<h2>2. Eligibility and accounts</h2><p>You must be at least 18 years old to create an account or enter into an agreement through the Platform. You are responsible for providing accurate information, protecting your login credentials and activity occurring through your account.</p>
<h2>3. Couple accounts and planning tools</h2><p>Couples may use features such as saved vendors, budgets, guest lists, reviews, inquiries, checklists and other planning tools. These resources are for general informational and organizational purposes and are not legal, financial, tax, insurance or other professional advice.</p>
<h2>4. Vendor information and relationships</h2><p>Vendor information can change. Couples should independently verify availability, pricing, licensing, insurance, services, contracts, deposits and cancellation terms directly with a vendor. My Portland Wedding is not a party to agreements between couples and independent vendors and does not guarantee a vendor’s quality, availability, pricing or performance.</p>
<h2>5. Featured and paid placement</h2><p>Some vendors purchase memberships that may provide enhanced visibility, priority positioning, badges or promotional exposure. Featured or paid placement is not a certification, endorsement or guarantee of a vendor’s services. My Portland Wedding may also feature businesses editorially.</p>
<h2>6. Reviews</h2><p>Reviews must reflect the submitter’s genuine experience and may not contain knowingly false statements, threats, harassment, unlawful content, spam, confidential information or unrelated material. We may moderate, reject or remove reviews that violate Platform policies or applicable law, and we do not guarantee publication of every review.</p>
<h2>7. User content</h2><p>By submitting photos, reviews, descriptions, logos or other material, you represent that you have the rights needed to submit it. You grant My Portland Wedding a non-exclusive, worldwide, royalty-free license to host, display, reproduce, resize, format and use that material as reasonably necessary to operate and promote the Platform and applicable listing. You retain ownership of your original content.</p>
<h2>8. Prohibited conduct</h2><p>You may not misuse the Platform, attempt unauthorized access, introduce malicious software, scrape the Platform at unreasonable scale, impersonate another person or business, submit fraudulent information, manipulate reviews, interfere with Platform operation or use the Platform for unlawful purposes.</p>
<h2>9. Intellectual property</h2><p>The My Portland Wedding name, branding, original website design, written content, graphics, software and other original Platform materials are owned by My Portland Wedding or its licensors and are protected by applicable intellectual-property laws.</p>
<h2>10. Platform availability</h2><p>We may modify, suspend, add or discontinue features when reasonably necessary. We do not guarantee uninterrupted or error-free availability.</p>
<h2>11. Disclaimer and limitation of liability</h2><p>To the extent permitted by law, the Platform is provided “as is” and “as available.” My Portland Wedding does not guarantee that any listing, recommendation, review or planning resource will meet a user’s requirements. To the fullest extent permitted by law, My Portland Wedding will not be liable for indirect, incidental, special, consequential, exemplary or punitive damages arising from use of the Platform or transactions between users and independent vendors. Nothing here excludes liability that cannot legally be excluded.</p>
<h2>12. Changes and governing law</h2><p>We may update these Terms periodically and will post the current version and effective date. These Terms are governed by Oregon law, without regard to conflict-of-law principles, except where applicable law requires otherwise.</p>
<h2>13. Contact</h2><p>Questions may be sent to <a href="mailto:hello@myportlandwedding.com">hello@myportlandwedding.com</a>.</p>
<p className="legalNote">Consumers with couple accounts are also subject to our <Link href="/consumer-terms">Consumer Terms of Service</Link>. Paid wedding professionals are subject to our <Link href="/vendor-terms">Vendor Terms of Service</Link>. See our <Link href="/privacy-policy">Privacy Policy</Link> for information about data practices.</p>
</article></section></main>}
