import {NextResponse} from "next/server";import {createSupabaseServerClient} from "../../../../lib/supabase/server";import {createAdminClient} from "../../../../lib/supabase/admin";import {categories} from "../../../../lib/site";
async function ok(){const s=await createSupabaseServerClient(),{data:{user}}=await s.auth.getUser();if(!user)return false;return !!(await s.from("admin_users").select("user_id").eq("user_id",user.id).maybeSingle()).data}
const core=["venues","catering","photography","florists","djs","planners","cakes","hair-makeup"];
export async function POST(){if(!(await ok()))return NextResponse.json({error:"Unauthorized"},{status:401});const db=createAdminClient(),checks:any[]=[];const add=(id:string,group:string,name:string,status:string,detail:string)=>checks.push({id,group,name,status,detail});
const {data:v,error}=await db.from("vendor_profiles").select("id,business_name,primary_category,secondary_categories,plan,city,service_cities,pricing_from,pricing_typical,pricing_max,pricing_packages,wedding_styles,guest_capacity_min,guest_capacity_max,rating,status").eq("market_slug","portland").eq("status","active");if(error)return NextResponse.json({error:error.message},{status:500});const vendors=v||[],paid=vendors.filter((x:any)=>x.plan!=="free");
add("inventory","Builder inputs","Portland vendor inventory",vendors.length?"pass":"failed",`${vendors.length} active vendors loaded read-only; ${paid.length} paid/Builder-eligible.`);
for(const cat of core){const list=paid.filter((x:any)=>x.primary_category===cat||x.secondary_categories?.includes(cat)),priced=list.filter((x:any)=>x.pricing_from||x.pricing_typical||x.pricing_max||(x.pricing_packages||[]).length),area=list.filter((x:any)=>x.city==="Portland"||x.service_cities?.includes("Portland"));add("core:"+cat,"Core roster",categories.find(x=>x[0]===cat)?.[1]||cat,list.length>=2?"pass":list.length?"warning":"failed",`${list.length} eligible · ${priced.length} priced · ${area.length} explicitly serve Portland. Compare Other Matches needs at least 2.`)}
const withPricing=paid.filter((x:any)=>x.pricing_from||x.pricing_typical||x.pricing_max||(x.pricing_packages||[]).length),withStyle=paid.filter((x:any)=>(x.wedding_styles||[]).length),withArea=paid.filter((x:any)=>x.city==="Portland"||(x.service_cities||[]).length),withCapacity=paid.filter((x:any)=>x.guest_capacity_min||x.guest_capacity_max);
for(const [id,name,n] of [["pricing","Pricing data",withPricing.length],["style","Style matching data",withStyle.length],["area","Service-area data",withArea.length],["capacity","Guest-capacity data",withCapacity.length]] as const){const ratio=paid.length?n/paid.length:0;add("coverage:"+id,"Matching intelligence",name,ratio>=.7?"pass":ratio>=.4?"warning":"failed",`${n}/${paid.length} eligible vendors have this matching signal (${Math.round(ratio*100)}%).`)}
for(const [slug,label] of categories){const list=vendors.filter((x:any)=>x.primary_category===slug||x.secondary_categories?.includes(slug));add("market:"+slug,"Marketplace coverage",label,list.length?"pass":"warning",`${list.length} active listing(s) available.`)}
add("compare","Functional readiness","Compare / swap prerequisites",core.every(c=>paid.filter((x:any)=>x.primary_category===c||x.secondary_categories?.includes(c)).length>=2)?"pass":"warning","Each core roster category should have 2+ eligible vendors so a couple can compare or swap without hitting an empty state.");
add("budget","Functional readiness","Budget reallocation prerequisites",withPricing.length>=Math.max(4,Math.ceil(paid.length*.7))?"pass":"warning","Budget fitting depends on vendor pricing; this check requires strong pricing coverage before launch.");
add("safe","Scanner safety","No notifications or leads created","pass","This simulator only reads vendor_profiles. It does not call the Builder match/lead endpoints, consume quota, insert match events, create leads, or send email/push notifications.");
const totals={pass:checks.filter(x=>x.status==="pass").length,warning:checks.filter(x=>x.status==="warning").length,failed:checks.filter(x=>x.status==="failed").length};return NextResponse.json({finishedAt:new Date().toISOString(),totals,checks})}