import Link from "next/link";
import { plans } from "../../lib/site";
import TrackedLink from "../../components/TrackedLink";

export const metadata = {
  title: 'Join My Portland Wedding | Portland Wedding Vendors',
  description: 'Grow your visibility with My Portland Wedding vendor profiles, Wedding Builder opportunities, inquiries, analytics and local wedding planning exposure.',
  alternates: { canonical: '/for-vendors' },
  openGraph: { title: 'Join My Portland Wedding | Portland Wedding Vendors', description: 'Grow your visibility with My Portland Wedding vendor profiles, Wedding Builder opportunities, inquiries, analytics and local wedding planning exposure.', url: '/for-vendors', images: [{ url: '/brand/mpw-social-share.png', width: 1200, height: 630, alt: 'My Portland Wedding — Plan Local. Love Always.' }] }
};

export default function ForVendors(){return <main>
  <section className="pagehero vendorHero"><div className="container"><span className="eyebrow">For Portland wedding professionals</span><h1>Grow your wedding business locally.</h1><p className="meta vendorHeroCopy">Join My Portland Wedding to reach engaged couples planning in Portland and surrounding Oregon communities. Build a polished local profile, appear in vendor discovery and, on eligible paid plans, be considered for personalized Wedding Builder matches.</p><div className="heroButtons"><Link className="btn primary" href="#membership">Compare Memberships</Link><Link className="btn light" href="/vendor/login">Vendor Login</Link></div></div></section>
  <section className="section foundingLaunchSection"><div className="container"><div className="foundingLaunchCard"><div className="foundingLaunchCopy"><span className="foundingKicker">✦ Founding Vendor launch offer</span><h2>Premium for the Basic price. Locked in for as long as you stay.</h2><p>The first <strong>5 paid vendors in each wedding category</strong> can receive the full Premium membership for <strong>$35/month instead of $55/month</strong>, plus an exclusive Founding Vendor badge.</p><div className="foundingLaunchBenefits"><span>✦ Premium visibility</span><span>✦ Wedding Builder by My Portland Wedding opportunities</span><span>✦ Founding Vendor badge</span><span>✦ $20/month launch savings</span></div><small>*Founding pricing and badge eligibility continue while the membership remains continuously active. Free listings do not reserve a Founding Vendor position. Cancellation forfeits the founding benefit.</small></div><div className="foundingLaunchAction"><div className="fiveSpots"><span>1</span><span>2</span><span>3</span><span>4</span><span>5</span></div><strong>Only 5 paid founders per category</strong><TrackedLink className="btn gold" href="/vendor/signup?plan=basic" eventName="Founding Vendor CTA Clicked" eventProperties={{placement:"launch_offer"}}>Check My Category →</TrackedLink></div></div></div></section>
  <section className="section"><div className="container"><div className="grid vendorBenefits"><div className="benefit"><span className="eyebrow">01</span><h3>Get into Wedding Builder</h3><p>Paid vendors can be matched into personalized wedding rosters built around a couple’s budget, style, location and priorities—right when they are deciding who fits.</p></div><div className="benefit"><span className="eyebrow">02</span><h3>Show up beyond search</h3><p>Your profile, imagery, pricing and services can support category discovery, Wedding Builder matching and paid-tier exposure throughout MPW.</p></div><div className="benefit"><span className="eyebrow">03</span><h3>See what couples actually do</h3><p>Paid memberships connect discovery to measurable actions: profile views, saves, phone/email/website/social clicks, inquiries and Wedding Builder activity.</p></div></div></div></section>
  <section className="section sageSection" id="membership"><div className="container"><div className="sectionTitle"><span className="eyebrow">Vendor memberships</span><h2>Simple monthly memberships for Portland wedding pros.</h2><p className="meta sectionIntro">Start with a free local listing or choose a paid membership for richer profile features, direct contact tools, analytics, Wedding Builder eligibility and additional exposure across My Portland Wedding.</p></div><div className="grid plans fourPlans">{Object.entries(plans).map(([slug,p])=><div className={`plan ${slug==="professional"?"featured":""} ${slug==="free"?"freePlan":""}`} key={slug}>{slug==="professional"&&<span className="badge">Most Popular</span>}<h3>{p.name}</h3><div><span className="price">${p.price}</span>{p.price>0?"/month":" forever"}</div><ul>{p.features.map(x=><li key={x}>{x}</li>)}</ul><TrackedLink className={`btn ${slug==="premium"?"gold":slug==="free"?"light":"primary"}`} href={`/vendor/signup?plan=${slug}`} eventName="Vendor Plan CTA Clicked" eventProperties={{plan:slug,price:p.price}}>{slug==="free"?"Create Free Listing":`Choose ${p.name}`}</TrackedLink></div>)}</div><div className="billingPolicyCallout"><strong>Paid membership notice</strong><p>Basic, Pro and Premium memberships renew automatically each month at the selected plan rate until canceled. The Free listing has no charge and does not require payment checkout. To cancel a paid membership, vendors must notify My Portland Wedding by phone or email; cancellation is effective after confirmation by our team.</p></div></div></section>
  <section className="section"><div className="container vendorBottom"><span className="eyebrow">Already listed?</span><h2>Manage your profile anytime.</h2><p className="meta">Update your photos, services and business details from your vendor dashboard. Locked features will show exactly what you can unlock by upgrading.</p><Link className="btn light" href="/vendor/login">Vendor Login</Link></div></section>
</main>}
