import { NextRequest, NextResponse } from "next/server";
import { createSupabaseServerClient } from "../../../../lib/supabase/server";
export async function POST(req:NextRequest){
 if(process.env.VERCEL_ENV==="preview"||process.env.MPW_PREVIEW_MODE==="1") return NextResponse.redirect(new URL("/admin?message=Preview%20mode%3A%20vendor%20edit%20simulated",req.url),303);
 const form=await req.formData(); const supabase=await createSupabaseServerClient(); const {data:{user}}=await supabase.auth.getUser(); if(!user) return NextResponse.redirect(new URL("/admin/login",req.url),303); const {data:admin}=await supabase.from("admin_users").select("user_id").eq("user_id",user.id).maybeSingle(); if(!admin) return new NextResponse("Forbidden",{status:403});
 const id=String(form.get("vendor_id")||""); const allowedStatus=["draft","pending","active","suspended"]; const allowedPlan=["free","basic","professional","premium"]; const allowedStage=["lead","sold","setup_sent","payment_pending","active","paused","lost"];
 const status=String(form.get("status")||"pending"), plan=String(form.get("plan")||"basic"), stage=String(form.get("crm_stage")||"lead");
 const update={business_name:String(form.get("business_name")||"").trim(),email:String(form.get("email")||"").trim().toLowerCase()||null,phone:String(form.get("phone")||"").trim()||null,website:String(form.get("website")||"").trim()||null,plan:allowedPlan.includes(plan)?plan:"basic",status:allowedStatus.includes(status)?status:"pending",crm_stage:allowedStage.includes(stage)?stage:"lead",primary_category:String(form.get("primary_category")||"venues"),service_cities:form.getAll("service_cities").map(String),last_contact_at:String(form.get("last_contact_at")||"")||null,next_follow_up_at:String(form.get("next_follow_up_at")||"")||null,admin_notes:String(form.get("admin_notes")||"").trim()||null,updated_at:new Date().toISOString()};
 const {error}=await supabase.from("vendor_profiles").update(update).eq("id",id); const target=error?`/admin/vendors/${id}?error=${encodeURIComponent(error.message)}`:`/admin/vendors/${id}?message=${encodeURIComponent("Vendor updated")}`; return NextResponse.redirect(new URL(target,req.url),303);
}
